* Notebook [riksdagen_64_wikidata.ipynb](https://github.com/salgo60/SCB-Wikidata/blob/main/notebook/riksdagen_64_wikidata.ipynb) 
* [#64](https://github.com/salgo60/SCB-Wikidata/issues/64)
* result   
   * [html](https://salgo60.github.io/SCB-Wikidata/notebook/resultsRiksdagenWD/links_RiksdagenWikidata_v1_2026_02_08.html) 
   * [csv](https://salgo60.github.io/SCB-Wikidata/notebook/resultsRiksdagenWD/links_RiksdagenWikidata_v1_2026_02_08.csv)

In [1]:
import time

from datetime import datetime

now = datetime.now()
timestamp = now.timestamp()

start_time = time.time()
print("Start:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Start: 2026-02-12 10:20:26

In [2]:
WikidataInclude = False
SCRIPT_NAME = "riksdagen_64_wikidata.ipynb"
SCRIPT_URL = (
    "https://github.com/salgo60/SCB-Wikidata/"
    "blob/master/notebook/riksdagen_64_wikidata.ipynb"
)

In [3]:
import os

# Get the current working directory
current_directory = os.getcwd()
print("Current Working Directory:", current_directory)

Current Working Directory: /Users/salgo/Documents/GitHub/SCB-Wikidata/notebook

In [4]:
import requests

SESSION = requests.Session()
SESSION.headers.update({
    "User-Agent": "Mozilla/5.0 (compatible; URL-checker/1.0) salgo60@msn.com"
})

In [5]:
def read_domains(file_path):
    print(f"[DEBUG] Reading domains from: {file_path}")
    df = pd.read_csv(file_path, header=0)   # <- skip header row
    domains_list = df.iloc[:, 0].dropna().unique().tolist()
    print(f"[DEBUG] Found {len(domains_list)} domains.")
    return domains_list

In [6]:
import requests

def fetch_sitematrix_df():
    url = "https://meta.wikimedia.org/w/api.php"
    params = {
        "action": "sitematrix",
        "format": "json"
    }
    headers = {
        "User-Agent": "salgo60-language-fetcher/1.0 (salgo60@msn.com)"
    }

    print("[DEBUG] Fetching sitematrix…")
    r = requests.get(url, params=params, headers=headers)
    r.raise_for_status()

    if "application/json" not in r.headers.get("Content-Type", ""):
        raise ValueError("Server returned non-JSON response")

    data = r.json()["sitematrix"]

    rows = []

    # --- language-specific sites ---
    for key, lang_block in data.items():
        if not key.isdigit():
            continue  # skip "count", "specials"

        lang_code = lang_block.get("code")
        lang_name = lang_block.get("name")

        for site in lang_block.get("site", []):
            rows.append({
                "lang_code": lang_code,
                "lang_name": lang_name,
                "project": site.get("project"),
                "url": site.get("url"),
                "dbname": site.get("dbname"),
                "site_name": site.get("sitename"),
                "closed": site.get("closed", False)
            })

    # --- special wikis (Wikidata, Commons, Meta, etc.) ---
    for site in data.get("specials", []):
        rows.append({
            "lang_code": "special",
            "lang_name": "special",
            "project": site.get("project"),
            "url": site.get("url"),
            "dbname": site.get("dbname"),
            "site_name": site.get("sitename"),
            "closed": site.get("closed", False)
        })

    return pd.DataFrame(rows)

In [7]:
import requests
import pandas as pd


HEADERS = {
    "User-Agent": "salgo60-language-fetcher/2.0 (https://github.com/salgo60) salgo60@msn.com"
}


df_lang_fetch = fetch_sitematrix_df()
df_lang_fetch["closed"] = df_lang_fetch["closed"].fillna(False).astype(bool)

df_lang_wikipedia = df_lang_fetch[
    (df_lang_fetch["site_name"] == "Wikipedia") &
    (
        (df_lang_fetch["lang_name"].str.lower() != "special") |
        (df_lang_fetch["dbname"] == "wikidatawiki")
    )
]  

#df_lang_wikipedia.to_csv("test.csv")
df_lang_wikipedia.info()

[DEBUG] Fetching sitematrix…
<class 'pandas.core.frame.DataFrame'>
Index: 187 entries, 0 to 1047
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   lang_code  187 non-null    object
 1   lang_name  186 non-null    object
 2   project    0 non-null      object
 3   url        187 non-null    object
 4   dbname     187 non-null    object
 5   site_name  187 non-null    object
 6   closed     187 non-null    bool
dtypes: bool(1), object(6)
memory usage: 10.4+ KB

In [8]:
df_lang_wikipedia

,lang_code,lang_name,project,url,dbname,site_name,closed
0,aa,Qafár af,None,https://aa.wikipedia.org,aawiki,Wikipedia,False
5,ace,Acèh,None,https://ace.wikipedia.org,acewiki,Wikipedia,False
7,af,Afrikaans,None,https://af.wikipedia.org,afwiki,Wikipedia,False
11,ak,None,None,https://ak.wikipedia.org,akwiki,Wikipedia,False
18,ami,Pangcah,None,https://ami.wikipedia.org,amiwiki,Wikipedia,False
...,...,...,...,...,...,...,...
924,za,Vahcuengh,None,https://za.wikipedia.org,zawiki,Wikipedia,False
928,zea,Zeêuws,None,https://zea.wikipedia.org,zeawiki,Wikipedia,False
931,zh,中文,None,https://zh.wikipedia.org,zhwiki,Wikipedia,False
939,zu,isiZulu,None,https://zu.wikipedia.org,zuwiki,Wikipedia,False
1047,special,special,None,https://www.wikidata.org,wikidatawiki,Wikipedia,False

### Bara köra Wikidata

In [9]:
df_wd = df_lang_wikipedia[df_lang_wikipedia["lang_code"] == "special"]

In [10]:
df_wd

,lang_code,lang_name,project,url,dbname,site_name,closed
1047,special,special,None,https://www.wikidata.org,wikidatawiki,Wikipedia,False

In [11]:
def read_domains(file_path):
    print(f"[DEBUG] Reading domains from: {file_path}")
    df = pd.read_csv(file_path, header=0)   # <- skip header row
    domains_list = df.iloc[:, 0].dropna().unique().tolist()
    print(f"[DEBUG] Found {len(domains_list)} domains.")
    return domains_list

In [12]:
import os
import time
import random
import requests
import pandas as pd
from urllib.parse import urlparse
from tqdm.notebook import tqdm
file_path_domain = "sources/domains_riksdagen.csv"
domains = read_domains(file_path_domain)
print(domains)

[DEBUG] Reading domains from: sources/domains_riksdagen.csv
[DEBUG] Found 1 domains.
['riksdagen.se']

In [13]:
import requests

def fetch_sitematrix_df():
    url = "https://meta.wikimedia.org/w/api.php"
    params = {
        "action": "sitematrix",
        "format": "json"
    }
    headers = {
        "User-Agent": "salgo60-language-fetcher/1.0 (salgo60@msn.com)"
    }

    print("[DEBUG] Fetching sitematrix…")
    r = requests.get(url, params=params, headers=headers)
    r.raise_for_status()

    if "application/json" not in r.headers.get("Content-Type", ""):
        raise ValueError("Server returned non-JSON response")

    data = r.json()["sitematrix"]

    rows = []


    # --- special wikis (Wikidata, Commons, Meta, etc.) ---
    for site in data.get("specials", []):
        print(site)
        rows.append({
            "lang_code": "special",
            "lang_name": "special",
            "project": site.get("project"),
            "url": site.get("url"),
            "dbname": site.get("dbname"),
            "site_name": site.get("sitename"),
            "closed": site.get("closed", False)
        })

    return pd.DataFrame(rows)

In [14]:

df_wd.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 1047 to 1047
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   lang_code  1 non-null      object
 1   lang_name  1 non-null      object
 2   project    0 non-null      object
 3   url        1 non-null      object
 4   dbname     1 non-null      object
 5   site_name  1 non-null      object
 6   closed     1 non-null      bool
dtypes: bool(1), object(6)
memory usage: 57.0+ bytes

In [15]:
df_wd

,lang_code,lang_name,project,url,dbname,site_name,closed
1047,special,special,None,https://www.wikidata.org,wikidatawiki,Wikipedia,False

In [16]:
def resolve_api_base(lang):
    if lang == "special":
        # Wikidata (only valid "special" case in your pipeline)
        return "https://www.wikidata.org/w/api.php"

    return f"https://{lang}.wikipedia.org/w/api.php"

In [17]:
def request_timeout(lang):
    return 100 if lang == "special" else 10

In [18]:
import os

CHECKPOINT_FILE = "checkpoint_riksdagen_wd_links.parquet"

def load_checkpoint():
    if os.path.exists(CHECKPOINT_FILE):
        df_cp = pd.read_parquet(CHECKPOINT_FILE)
        print(f"Checkpoint hittad: {len(df_cp)} rader")
        return df_cp
    return pd.DataFrame()

In [19]:
# -----------------------------------------------------------
# Fetch exturlusage entries for one lang/domain
# -----------------------------------------------------------
def fetch_exturlusage(lang, domain):
    #base = f"https://{lang}.wikipedia.org/w/api.php"
    base = resolve_api_base(lang)
    params = {
        "action": "query",
        "format": "json",
        "list": "exturlusage",
        "euquery": domain,
        "eulimit": "max"
    }
    while True:
        #r = session.get(base, params=params, timeout=10)
        r = session.get(base, params=params, timeout=request_timeout(lang))        
        try:
            data = r.json()
        except ValueError:
            print(f"[WARN] {lang}: JSON decode failed")
            break

        for item in data.get("query", {}).get("exturlusage", []):
            yield {
                "lang": lang,
                "page_title": item.get("title"),
                "url": item.get("url"),
                "wiki_link": f"https://{lang}.wikipedia.org/wiki/{item.get('title').replace(' ', '_')}"
            }

        if "continue" not in data:
            break
        params.update(data["continue"])
        time.sleep(0.3)

In [20]:
df_wd

,lang_code,lang_name,project,url,dbname,site_name,closed
1047,special,special,None,https://www.wikidata.org,wikidatawiki,Wikipedia,False

In [21]:
domains

['riksdagen.se']

In [22]:
UseWDCache = True  # True = använd cache, False = hämta från WD
CACHE_FILE = "riksdagen_wd_cache.json"

In [23]:
import json
import os

if os.path.exists(CACHE_FILE):
    with open(CACHE_FILE, "r", encoding="utf-8") as f:
        cache = json.load(f)
else:
    cache = {}

In [24]:
def fetch_with_cache(lang, domains):
    global cache

    key = f"{lang}|{'|'.join(domains)}"

    # --- Läs från cache ---
    if UseWDCache:
        if key in cache:
            print("CACHE HIT:", key)
            return cache[key]
        else:
            print("CACHE MISS (UseWDCache=True):", key)
            return []

    # --- Hämta från WD ---
    data = list(fetch_exturlusage(lang, domains))

    cache[key] = data

    # skriv till fil direkt (säkert vid långa körningar)
    with open(CACHE_FILE, "w", encoding="utf-8") as f:
        json.dump(cache, f)

    return data

In [25]:

# -------------------------
# Session & helpers
# -------------------------
session = requests.Session()
session.headers.update({"User-Agent": "SCB-LinkAudit/1.0 salgo60@msn.com"})


print("Antal Språk:",len(df_wd))

results = []



results = []

for _, row in df_wd.iterrows():
    lang = row["lang_code"]
    url  = row["url"]
    lang_name = row["lang_name"]

    before = len(results)

    print(lang, url, lang_name, domains)

    entries = fetch_with_cache(lang, domains)
    results.extend(entries)

    after = len(results)
    print(lang, url, lang_name, "-", after-before)

Antal Språk: 1
special https://www.wikidata.org special ['riksdagen.se']
CACHE HIT: special|riksdagen.se
special https://www.wikidata.org special - 617191

In [26]:
df_riksdagen_wd = pd.DataFrame(results)
df_riksdagen_wd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 617191 entries, 0 to 617190
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   lang        617191 non-null  object
 1   page_title  617191 non-null  object
 2   url         617191 non-null  object
 3   wiki_link   617191 non-null  object
dtypes: object(4)
memory usage: 18.8+ MB

In [27]:
import pandas as pd

# --- Stats ---
total_links = len(df_riksdagen_wd)
total_unique_links = df_riksdagen_wd['url'].nunique()
num_languages = df_riksdagen_wd['lang'].nunique()
langs_sorted = df_riksdagen_wd['lang'].value_counts()

print("Total links:", total_links)
print("Total unique links:", total_unique_links)
print("Wikidata")

Total links: 617191
Total unique links: 614687
Wikidata

### Check url

In [28]:
import requests 
from requests.exceptions import RequestException 
from concurrent.futures import ThreadPoolExecutor, as_completed 
from tqdm import tqdm 
import pandas as pd 
import time  
import threading

In [29]:
MAX_WORKERS = 64              # För IO-bound scraping kan du ofta köra 32–128 workers
MAX_WORKERS = min(128, os.cpu_count()*10)
REQUEST_TIMEOUT = 15

RATE_LIMIT_PER_SEC = 2       # max requests/sek totalt
BACKOFF_FACTOR = 2
MAX_RETRIES = 3

CHECKPOINT_EVERY = 500
CHUNK_SIZE = 5000

CHECKPOINT_FILE = "checkpoint_riksdagen_wikidata.parquet"

In [30]:
import threading
import time

rate_lock = threading.Lock()
last_request_time = 0

def wait_for_rate_limit():
    global last_request_time
    
    with rate_lock:
        now = time.time()
        wait = 1 / RATE_LIMIT_PER_SEC - (now - last_request_time)
        if wait > 0:
            time.sleep(wait)
        last_request_time = time.time()

In [31]:
def request_with_retry(method, url, session, **kwargs):
    delay = 1
    
    for attempt in range(MAX_RETRIES):
        try:
            wait_for_rate_limit()
            return session.request(method, url, **kwargs)
        
        except RequestException:
            if attempt == MAX_RETRIES - 1:
                raise
            time.sleep(delay)
            delay *= BACKOFF_FACTOR

In [32]:
def check_url(url: str) -> dict:
    session = get_session()

    try:
        r = request_with_retry(
            "HEAD",
            url,
            session,
            allow_redirects=False,
            timeout=REQUEST_TIMEOUT,
        )
    except RequestException as e:
        return {"url": url, "status": "error", "reason": str(e)}

    final_url = r.url

    if r.status_code >= 400:
        return {"url": url, "status": "dead", "reason": f"HTTP {r.status_code}"}

    if norm(final_url) == norm(ROOT_CANONICAL) and norm(url) != norm(final_url):
        return {"url": url, "status": "dead", "reason": "redirect_to_root"}

    try:
        r = request_with_retry(
            "GET",
            final_url,
            session,
            allow_redirects=True,
            timeout=REQUEST_TIMEOUT,
        )
    except RequestException as e:
        return {"url": url, "status": "error", "reason": str(e)}

    if looks_like_soft_404(r):
        return {"url": url, "status": "dead", "reason": "soft_404"}

    return {"url": url, "status": "ok"}

In [33]:
import os

def load_checkpoint():
    if os.path.exists(CHECKPOINT_FILE):
        return pd.read_parquet(CHECKPOINT_FILE)
    return pd.DataFrame()

In [34]:
from itertools import islice

def chunks(iterable, size):
    it = iter(iterable)
    while chunk := list(islice(it, size)):
        yield chunk

In [35]:
# ========================== # Internet Archive # ========================== 
def check_internet_archive(url: str) -> str | None: 
    session = get_session() 
    api = "https://archive.org/wayback/available" 
    
    try: 
        r = session.get( api, 
                        params={"url": url}, 
                        timeout=10, ) 
        data = r.json() 
    except Exception: 
        return None 
    snap = data.get("archived_snapshots", {}).get("closest") 
    if snap and snap.get("available"): 
        return snap.get("url") 
    return None

In [36]:


def is_worth_checking(url: str) -> bool: 
    if not url.startswith("http"):
        return False 
    if "riksdagen.se" not in url: 
        return False 
    return True

In [37]:
# ========================== # Worker # ========================== 
def process_url(url: str) -> dict: 
    result = check_url(url) 
    if result["status"] == "dead": 
        ia_url = check_internet_archive(url) 
        result["ia_url"] = ia_url 
        result["ia_status"] = "available" if ia_url else "missing" 
    else: 
        result["ia_url"] = None 
        result["ia_status"] = "skipped" 
    return result

In [38]:
def run(df):

    urls_all = [
        u for u in df["url"].dropna().astype(str).unique()
        if is_worth_checking(u)
    ]

    cp = load_checkpoint()
    done = set(cp["url"]) if not cp.empty else set()

    urls_remaining = [u for u in urls_all if u not in done]

    print("Totalt:", len(urls_all))
    print("Redan klara:", len(done))
    print("Kvar:", len(urls_remaining))
    print("MAX_WORKERS:", MAX_WORKERS)

    results = cp.to_dict("records") if not cp.empty else []

    processed_since_log = 0

    for chunk_idx, chunk in enumerate(chunks(urls_remaining, CHUNK_SIZE), 1):

        print(f"\nStartar chunk {chunk_idx} ({len(chunk)} URL:er)")

        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
            futures = [ex.submit(process_url, u) for u in chunk]

            from tqdm import tqdm

            for chunk_idx, chunk in enumerate(chunks(urls_remaining, CHUNK_SIZE), 1):
            
                print(f"\nStartar chunk {chunk_idx} ({len(chunk)} URL:er)")
            
                with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
                    futures = [ex.submit(process_url, u) for u in chunk]
            
                    for f in tqdm(
                        as_completed(futures),
                        total=len(futures),
                        desc=f"Chunk {chunk_idx}",
                    ):
                        res = f.result()
                        results.append(res)
            
                        processed_since_log += 1
            
                        # --- Logga var 500:e ---
                        if processed_since_log >= 500:
                            print(f"{len(results)} totalt klara...")
                            processed_since_log = 0
            
                        # --- Checkpoint ---
                        if len(results) % CHECKPOINT_EVERY == 0:
                            tmp = CHECKPOINT_FILE + ".tmp"
                            pd.DataFrame(results).to_parquet(tmp)
                            os.replace(tmp, CHECKPOINT_FILE)
                            print(f"Checkpoint sparad ({len(results)})")

    df_final = pd.DataFrame(results)
    df_final.to_parquet("final.parquet")

    print("\nKLAR.")
    print("Totalt processade:", len(df_final))

    return df_final

In [39]:

import requests
import threading

USER_AGENT = "LinkChecker/1.0 salgo60@msn.com"

thread_local = threading.local()

def get_session():
    if not hasattr(thread_local, "session"):
        s = requests.Session()
        s.headers.update({"User-Agent": USER_AGENT})
        thread_local.session = s
    return thread_local.session


def norm(u: str) -> str:
    return u.rstrip("/").lower()


def is_worth_checking(url: str) -> bool:
    return url.startswith("http") and "riksdagen.se" in url

In [40]:
def looks_like_soft_404(response) -> bool:
    text = (response.text or "").lower()

    for phrase in SOFT_404_PHRASES:
        if phrase in text:
            return True

    if "<title>" in text:
        title = text.split("<title>", 1)[1].split("</title>", 1)[0]
        if "404" in title.lower():
            return True
        if "sidan finns inte" in title.lower():
            return True

    return False

SOFT_404_PHRASES = [
    "sidan kan inte hittas",
    "sidan tagits bort",
    "felaktig adress",
    "kontakta registrator",
    "sidan finns inte",
    "den här sidan kan inte visas",
    "Hoppsan! Vi kunde tyvärr inte hitta sidan"
]

USER_AGENT = "LinkChecker/1.0 (research; salgo60@msn.com)"

In [41]:
ROOT_CANONICAL = "https://www.riksdagen.se"

In [ ]:
df_result = run(df_riksdagen_wd)

from datetime import date
import os

# Sätt datum
today = date.today().strftime("%Y_%m_%d")

# Se till att katalogen finns
os.makedirs("resultsRiksdagenWD", exist_ok=True)

# Bygg filnamn
outfile = f"resultsRiksdagenWD/links_Riksdagen_v1_Wikidata_{today}.csv"
    
# Exportera
df_riksdagen_wd.to_csv(outfile, index=False, encoding="utf-8")

print(f"[OK] Exported {len(df_riksdagen_wd)} rows to {outfile}")

Totalt: 614687
Redan klara: 134000
Kvar: 480687
MAX_WORKERS: 80

Startar chunk 1 (5000 URL:er)

Startar chunk 1 (5000 URL:er)

Chunk 1:  10%|███                            | 500/5000 [18:18<45:19,  1.65it/s]

134500 totalt klara...
Checkpoint sparad (134500)

Chunk 1:  20%|█████▊                       | 999/5000 [51:01<1:04:38,  1.03it/s]

135000 totalt klara...

Chunk 1:  20%|█████▌                      | 1000/5000 [51:02<1:01:09,  1.09it/s]

Checkpoint sparad (135000)

Chunk 1:  30%|████████▍                   | 1500/5000 [1:07:27<59:42,  1.02s/it]

135500 totalt klara...
Checkpoint sparad (135500)

Chunk 1:  40%|██████████▍               | 2000/5000 [1:24:42<4:36:12,  5.52s/it]

136000 totalt klara...
Checkpoint sparad (136000)

Chunk 1:  50%|█████████████▉              | 2499/5000 [1:41:43<44:59,  1.08s/it]

136500 totalt klara...

Chunk 1:  50%|██████████████              | 2500/5000 [1:41:44<49:22,  1.19s/it]

Checkpoint sparad (136500)

Chunk 1:  60%|████████████████▊           | 2999/5000 [1:58:08<32:23,  1.03it/s]

137000 totalt klara...

Chunk 1:  60%|████████████████▊           | 3000/5000 [1:58:09<30:33,  1.09it/s]

Checkpoint sparad (137000)

Chunk 1:  70%|███████████████████▌        | 3499/5000 [2:14:33<29:08,  1.16s/it]

137500 totalt klara...

Chunk 1:  70%|███████████████████▌        | 3500/5000 [2:14:34<28:04,  1.12s/it]

Checkpoint sparad (137500)

Chunk 1:  80%|██████████████████████▍     | 3999/5000 [2:31:36<40:31,  2.43s/it]

138000 totalt klara...

Chunk 1:  80%|████████████████████▊     | 4000/5000 [2:31:49<1:33:09,  5.59s/it]

Checkpoint sparad (138000)

Chunk 1:  90%|█████████████████████████▏  | 4499/5000 [2:48:52<09:34,  1.15s/it]

138500 totalt klara...

Chunk 1:  90%|█████████████████████████▏  | 4500/5000 [2:48:53<08:35,  1.03s/it]

Checkpoint sparad (138500)

Chunk 1: 100%|███████████████████████████▉| 4999/5000 [3:04:34<00:00,  2.00it/s]

139000 totalt klara...

Chunk 1: 100%|████████████████████████████| 5000/5000 [3:04:35<00:00,  2.22s/it]

Checkpoint sparad (139000)

Startar chunk 2 (5000 URL:er)

Chunk 2:  10%|███                            | 500/5000 [08:57<43:27,  1.73it/s]

139500 totalt klara...
Checkpoint sparad (139500)

Chunk 2:  20%|██████                        | 1000/5000 [17:10<36:45,  1.81it/s]

140000 totalt klara...
Checkpoint sparad (140000)

Chunk 2:  30%|█████████                     | 1500/5000 [25:23<31:36,  1.85it/s]

140500 totalt klara...
Checkpoint sparad (140500)

Chunk 2:  40%|████████████                  | 2000/5000 [50:22<57:37,  1.15s/it]

141000 totalt klara...
Checkpoint sparad (141000)

Chunk 2:  50%|██████████████              | 2500/5000 [2:11:24<47:57,  1.15s/it]

141500 totalt klara...
Checkpoint sparad (141500)

Chunk 2:  60%|████████████████▊           | 2999/5000 [3:10:33<31:45,  1.05it/s]

142000 totalt klara...

Chunk 2:  60%|████████████████▊           | 3000/5000 [3:10:35<35:50,  1.08s/it]

Checkpoint sparad (142000)

Chunk 2:  70%|███████████████████▌        | 3500/5000 [4:30:31<56:02,  2.24s/it]

142500 totalt klara...
Checkpoint sparad (142500)

Chunk 2:  80%|██████████████████████▍     | 3999/5000 [5:07:29<18:26,  1.11s/it]

143000 totalt klara...

Chunk 2:  80%|██████████████████████▍     | 4000/5000 [5:07:30<16:52,  1.01s/it]

Checkpoint sparad (143000)

Chunk 2:  90%|█████████████████████████▏  | 4500/5000 [5:15:50<05:46,  1.44it/s]

143500 totalt klara...
Checkpoint sparad (143500)

Chunk 2: 100%|████████████████████████████| 5000/5000 [5:23:56<00:00,  3.89s/it]

144000 totalt klara...
Checkpoint sparad (144000)

Startar chunk 3 (5000 URL:er)

Chunk 3:  10%|███                            | 500/5000 [08:56<42:09,  1.78it/s]

144500 totalt klara...
Checkpoint sparad (144500)

Chunk 3:  20%|██████                        | 1000/5000 [17:12<36:33,  1.82it/s]

145000 totalt klara...
Checkpoint sparad (145000)

Chunk 3:  30%|█████████                     | 1500/5000 [25:28<30:50,  1.89it/s]

145500 totalt klara...
Checkpoint sparad (145500)

Chunk 3:  40%|████████████                  | 2000/5000 [33:44<27:32,  1.82it/s]

146000 totalt klara...
Checkpoint sparad (146000)

Chunk 3:  50%|███████████████               | 2500/5000 [59:41<43:45,  1.05s/it]

146500 totalt klara...
Checkpoint sparad (146500)

Chunk 3:  60%|████████████████▊           | 3000/5000 [1:08:04<19:04,  1.75it/s]

147000 totalt klara...
Checkpoint sparad (147000)

Chunk 3:  70%|███████████████████▌        | 3500/5000 [1:16:27<26:10,  1.05s/it]

147500 totalt klara...
Checkpoint sparad (147500)

Chunk 3:  80%|██████████████████████▍     | 4000/5000 [1:24:52<17:17,  1.04s/it]

148000 totalt klara...
Checkpoint sparad (148000)

Chunk 3:  90%|█████████████████████████▏  | 4500/5000 [1:33:26<08:54,  1.07s/it]

148500 totalt klara...
Checkpoint sparad (148500)

Chunk 3: 100%|████████████████████████████| 5000/5000 [1:41:28<00:00,  1.22s/it]

149000 totalt klara...
Checkpoint sparad (149000)

Startar chunk 4 (5000 URL:er)

Chunk 4:  10%|███                            | 500/5000 [08:56<41:19,  1.81it/s]

149500 totalt klara...
Checkpoint sparad (149500)

Chunk 4:  20%|██████                        | 1000/5000 [17:12<35:55,  1.86it/s]

150000 totalt klara...
Checkpoint sparad (150000)

Chunk 4:  30%|████████▉                     | 1499/5000 [25:24<29:35,  1.97it/s]

150500 totalt klara...

Chunk 4:  30%|█████████                     | 1501/5000 [25:25<27:25,  2.13it/s]

Checkpoint sparad (150500)

Chunk 4:  40%|███████████▉                  | 1999/5000 [33:38<25:13,  1.98it/s]

151000 totalt klara...

Chunk 4:  40%|████████████                  | 2000/5000 [33:39<29:15,  1.71it/s]

Checkpoint sparad (151000)

Chunk 4:  50%|██████████████▉               | 2499/5000 [42:32<21:46,  1.91it/s]

151500 totalt klara...

Chunk 4:  50%|███████████████               | 2501/5000 [42:33<20:11,  2.06it/s]

Checkpoint sparad (151500)

Chunk 4:  60%|██████████████████            | 3000/5000 [50:47<18:39,  1.79it/s]

152000 totalt klara...
Checkpoint sparad (152000)

Chunk 4:  70%|█████████████████████         | 3500/5000 [59:03<13:58,  1.79it/s]

152500 totalt klara...
Checkpoint sparad (152500)

Chunk 4:  80%|██████████████████████▍     | 4000/5000 [1:07:19<09:17,  1.79it/s]

153000 totalt klara...
Checkpoint sparad (153000)

Chunk 4:  90%|█████████████████████████▏  | 4499/5000 [1:16:14<04:24,  1.89it/s]

153500 totalt klara...

Chunk 4:  90%|█████████████████████████▏  | 4500/5000 [1:16:15<04:54,  1.70it/s]

Checkpoint sparad (153500)

Chunk 4:  92%|█████████████████████████▋  | 4591/5000 [1:17:41<03:28,  1.96it/s]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Chunk 7:  10%|███                            | 499/5000 [08:52<39:22,  1.91it/s]

164500 totalt klara...

Chunk 7:  10%|███                            | 500/5000 [08:53<49:48,  1.51it/s]

Checkpoint sparad (164500)

Chunk 7:  20%|██████▏                        | 999/5000 [17:05<33:43,  1.98it/s]

165000 totalt klara...

Chunk 7:  20%|██████                        | 1000/5000 [17:06<49:09,  1.36it/s]

Checkpoint sparad (165000)

Chunk 7:  30%|████████▉                     | 1499/5000 [25:18<30:17,  1.93it/s]

165500 totalt klara...

Chunk 7:  30%|█████████                     | 1501/5000 [25:19<27:24,  2.13it/s]

Checkpoint sparad (165500)

Chunk 7:  40%|███████████▉                  | 1999/5000 [33:33<25:29,  1.96it/s]

166000 totalt klara...

Chunk 7:  40%|████████████                  | 2000/5000 [33:34<30:18,  1.65it/s]

Checkpoint sparad (166000)

Chunk 7:  50%|██████████████▉               | 2499/5000 [42:27<21:56,  1.90it/s]

166500 totalt klara...

Chunk 7:  50%|███████████████               | 2500/5000 [42:27<24:15,  1.72it/s]

Checkpoint sparad (166500)

Chunk 7:  60%|██████████████████            | 3000/5000 [50:41<18:33,  1.80it/s]

167000 totalt klara...
Checkpoint sparad (167000)

Chunk 7:  70%|████████████████████▉         | 3499/5000 [58:54<12:42,  1.97it/s]

167500 totalt klara...

Chunk 7:  70%|█████████████████████         | 3500/5000 [58:55<16:26,  1.52it/s]

Checkpoint sparad (167500)

Chunk 7:  80%|██████████████████████▍     | 4000/5000 [1:07:08<09:17,  1.80it/s]

168000 totalt klara...
Checkpoint sparad (168000)

Chunk 7:  87%|████████████████████████▍   | 4354/5000 [1:13:27<05:22,  2.00it/s]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Chunk 9:  60%|█████████████████▉            | 2999/5000 [50:39<16:52,  1.98it/s]

177000 totalt klara...

Chunk 9:  60%|██████████████████            | 3000/5000 [50:40<19:09,  1.74it/s]

Checkpoint sparad (177000)

Chunk 9:  70%|████████████████████▉         | 3499/5000 [58:54<12:26,  2.01it/s]

177500 totalt klara...

Chunk 9:  70%|█████████████████████         | 3500/5000 [58:55<18:37,  1.34it/s]

Checkpoint sparad (177500)

Chunk 9:  80%|██████████████████████▍     | 3999/5000 [1:07:08<08:29,  1.97it/s]

178000 totalt klara...

Chunk 9:  80%|██████████████████████▍     | 4000/5000 [1:07:09<11:34,  1.44it/s]

Checkpoint sparad (178000)

Chunk 9:  90%|█████████████████████████▏  | 4499/5000 [1:16:01<04:22,  1.91it/s]

178500 totalt klara...

Chunk 9:  90%|█████████████████████████▏  | 4500/5000 [1:16:02<05:40,  1.47it/s]

Checkpoint sparad (178500)

Chunk 9: 100%|███████████████████████████▉| 4999/5000 [1:23:55<00:00,  1.97it/s]

179000 totalt klara...

Chunk 9: 100%|████████████████████████████| 5000/5000 [1:23:56<00:00,  1.01s/it]

Checkpoint sparad (179000)

Startar chunk 10 (5000 URL:er)

Chunk 10:  10%|██▉                           | 499/5000 [08:52<39:16,  1.91it/s]

179500 totalt klara...

Chunk 10:  10%|███                           | 501/5000 [08:53<36:05,  2.08it/s]

Checkpoint sparad (179500)

Chunk 10:  20%|█████▉                        | 999/5000 [17:06<34:09,  1.95it/s]

180000 totalt klara...

Chunk 10:  20%|█████▊                       | 1000/5000 [17:07<41:59,  1.59it/s]

Checkpoint sparad (180000)

Chunk 10:  30%|███████▍                 | 1499/5000 [1:07:28<1:38:09,  1.68s/it]

180500 totalt klara...

Chunk 10:  30%|███████▌                 | 1501/5000 [1:07:30<1:13:44,  1.26s/it]

Checkpoint sparad (180500)

Chunk 10:  40%|██████████▊                | 1999/5000 [1:53:02<42:09,  1.19it/s]

181000 totalt klara...

Chunk 10:  40%|██████████▊                | 2000/5000 [1:53:02<42:53,  1.17it/s]

Checkpoint sparad (181000)

Chunk 10:  50%|████████████▍            | 2499/5000 [2:01:45<1:59:17,  2.86s/it]

181500 totalt klara...

Chunk 10:  50%|████████████▌            | 2500/5000 [2:01:47<1:51:55,  2.69s/it]

Checkpoint sparad (181500)

Chunk 10:  60%|████████████████▏          | 2999/5000 [2:10:06<22:33,  1.48it/s]

182000 totalt klara...

Chunk 10:  60%|████████████████▏          | 3000/5000 [2:10:07<23:32,  1.42it/s]

Checkpoint sparad (182000)

Chunk 10:  70%|██████████████████▉        | 3499/5000 [2:18:19<12:47,  1.96it/s]

182500 totalt klara...

Chunk 10:  70%|██████████████████▉        | 3500/5000 [2:18:20<16:00,  1.56it/s]

Checkpoint sparad (182500)

Chunk 10:  80%|█████████████████████▌     | 3999/5000 [2:26:35<12:47,  1.30it/s]

183000 totalt klara...

Chunk 10:  80%|█████████████████████▌     | 4000/5000 [2:26:36<12:48,  1.30it/s]

Checkpoint sparad (183000)

Chunk 10:  90%|████████████████████████▎  | 4499/5000 [2:35:19<23:54,  2.86s/it]

183500 totalt klara...

Chunk 10:  90%|████████████████████████▎  | 4500/5000 [2:35:21<23:18,  2.80s/it]

Checkpoint sparad (183500)

Chunk 10: 100%|██████████████████████████▉| 4999/5000 [2:43:13<00:00,  1.98it/s]

184000 totalt klara...

Chunk 10: 100%|███████████████████████████| 5000/5000 [2:43:14<00:00,  1.96s/it]

Checkpoint sparad (184000)

Startar chunk 11 (5000 URL:er)

Chunk 11:  20%|█████▉                        | 999/5000 [17:05<33:27,  1.99it/s]

185000 totalt klara...

Chunk 11:  20%|█████▊                       | 1000/5000 [17:07<56:23,  1.18it/s]

Checkpoint sparad (185000)

Chunk 11:  30%|████████▋                    | 1499/5000 [25:19<29:22,  1.99it/s]

185500 totalt klara...

Chunk 11:  30%|████████▋                    | 1500/5000 [25:20<38:20,  1.52it/s]

Checkpoint sparad (185500)

Chunk 11:  40%|███████████▌                 | 1999/5000 [33:33<25:28,  1.96it/s]

186000 totalt klara...

Chunk 11:  40%|███████████▌                 | 2000/5000 [33:34<35:54,  1.39it/s]

Checkpoint sparad (186000)

Chunk 11:  50%|██████████████▍              | 2499/5000 [42:26<21:47,  1.91it/s]

186500 totalt klara...

Chunk 11:  50%|██████████████▌              | 2500/5000 [42:28<29:44,  1.40it/s]

Checkpoint sparad (186500)

Chunk 11:  60%|█████████████████▍           | 2999/5000 [50:40<16:54,  1.97it/s]

187000 totalt klara...

Chunk 11:  60%|█████████████████▍           | 3000/5000 [50:41<21:17,  1.57it/s]

Checkpoint sparad (187000)

Chunk 11:  70%|████████████████████▎        | 3499/5000 [58:53<12:37,  1.98it/s]

187500 totalt klara...

Chunk 11:  70%|████████████████████▎        | 3500/5000 [58:54<15:43,  1.59it/s]

Checkpoint sparad (187500)

Chunk 11:  71%|███████████████████▏       | 3554/5000 [1:00:01<12:05,  1.99it/s]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Chunk 12:  90%|████████████████████████▎  | 4499/5000 [1:16:02<04:20,  1.93it/s]

193500 totalt klara...

Chunk 12:  90%|████████████████████████▎  | 4502/5000 [1:16:03<03:44,  2.22it/s]

Checkpoint sparad (193500)

Chunk 13:  70%|██████████████████▉        | 3499/5000 [1:00:05<12:33,  1.99it/s]

197500 totalt klara...

Chunk 13:  70%|██████████████████▉        | 3500/5000 [1:00:06<19:29,  1.28it/s]

Checkpoint sparad (197500)

Chunk 13:  80%|█████████████████████▌     | 3999/5000 [1:08:18<08:20,  2.00it/s]

198000 totalt klara...

Chunk 13:  80%|█████████████████████▌     | 4000/5000 [1:08:20<12:22,  1.35it/s]

Checkpoint sparad (198000)

Chunk 17:  30%|████████▋                    | 1499/5000 [25:18<29:09,  2.00it/s]

215500 totalt klara...

Chunk 17:  30%|████████▋                    | 1502/5000 [25:20<26:19,  2.22it/s]

Checkpoint sparad (215500)

Chunk 17:  50%|██████████████▍              | 2499/5000 [42:26<21:35,  1.93it/s]

216500 totalt klara...

Chunk 17:  50%|██████████████▌              | 2500/5000 [42:27<25:02,  1.66it/s]

Checkpoint sparad (216500)

Chunk 17:  60%|█████████████████▍           | 2999/5000 [50:40<16:35,  2.01it/s]

217000 totalt klara...

Chunk 17:  60%|█████████████████▍           | 3000/5000 [50:41<23:05,  1.44it/s]

Checkpoint sparad (217000)

Chunk 17:  70%|████████████████████▎        | 3499/5000 [58:55<12:33,  1.99it/s]

217500 totalt klara...

Chunk 17:  70%|████████████████████▎        | 3500/5000 [58:55<16:11,  1.54it/s]

Checkpoint sparad (217500)

Chunk 17:  80%|█████████████████████▌     | 3999/5000 [1:07:10<08:21,  2.00it/s]

218000 totalt klara...

Chunk 17:  80%|█████████████████████▌     | 4000/5000 [1:07:11<11:07,  1.50it/s]

Checkpoint sparad (218000)

Chunk 17:  90%|████████████████████████▎  | 4499/5000 [1:16:04<04:19,  1.93it/s]

218500 totalt klara...

Chunk 17:  90%|████████████████████████▎  | 4500/5000 [1:16:05<06:52,  1.21it/s]

Checkpoint sparad (218500)

Chunk 18:  30%|████████▋                    | 1499/5000 [25:23<29:34,  1.97it/s]

220500 totalt klara...

Chunk 18:  30%|████████▋                    | 1500/5000 [25:24<41:33,  1.40it/s]

Checkpoint sparad (220500)

Chunk 18:  40%|███████████▌                 | 1999/5000 [33:37<25:13,  1.98it/s]

221000 totalt klara...

Chunk 18:  40%|███████████▌                 | 2000/5000 [33:38<29:41,  1.68it/s]

Checkpoint sparad (221000)

Chunk 18:  50%|██████████████▍              | 2499/5000 [42:31<21:29,  1.94it/s]

221500 totalt klara...

Chunk 18:  50%|██████████████▌              | 2500/5000 [42:32<24:06,  1.73it/s]

Checkpoint sparad (221500)

Chunk 18:  70%|████████████████████▎        | 3500/5000 [58:59<13:50,  1.81it/s]

222500 totalt klara...
Checkpoint sparad (222500)

Chunk 18:  80%|█████████████████████▌     | 3999/5000 [1:07:12<08:23,  1.99it/s]

223000 totalt klara...

Chunk 18:  80%|█████████████████████▌     | 4000/5000 [1:07:13<09:36,  1.74it/s]

Checkpoint sparad (223000)

Chunk 19:  70%|████████████████████▎        | 3500/5000 [59:01<13:57,  1.79it/s]

227500 totalt klara...
Checkpoint sparad (227500)

Chunk 19:  80%|█████████████████████▌     | 3999/5000 [1:07:16<08:32,  1.95it/s]

228000 totalt klara...

Chunk 19:  80%|█████████████████████▌     | 4000/5000 [1:07:16<10:02,  1.66it/s]

Checkpoint sparad (228000)

Chunk 19:  90%|████████████████████████▎  | 4499/5000 [1:16:12<04:33,  1.83it/s]

228500 totalt klara...

Chunk 19:  90%|████████████████████████▎  | 4500/5000 [1:16:13<04:45,  1.75it/s]

Checkpoint sparad (228500)

Chunk 19: 100%|██████████████████████████▉| 4999/5000 [1:24:08<00:00,  1.96it/s]

229000 totalt klara...

Chunk 19: 100%|███████████████████████████| 5000/5000 [1:24:09<00:00,  1.01s/it]

Checkpoint sparad (229000)

Startar chunk 20 (5000 URL:er)

Chunk 20:  10%|██▉                           | 499/5000 [08:55<39:22,  1.91it/s]

229500 totalt klara...

Chunk 20:  10%|███                           | 501/5000 [08:55<35:55,  2.09it/s]

Checkpoint sparad (229500)

Chunk 20:  20%|█████▊                       | 1000/5000 [17:11<36:59,  1.80it/s]

230000 totalt klara...
Checkpoint sparad (230000)

Chunk 20:  30%|████████▋                    | 1499/5000 [25:26<29:43,  1.96it/s]

230500 totalt klara...

Chunk 20:  30%|████████▋                    | 1500/5000 [25:27<33:04,  1.76it/s]

Checkpoint sparad (230500)

Chunk 20:  40%|███████████▌                 | 1999/5000 [33:42<25:19,  1.98it/s]

231000 totalt klara...

Chunk 20:  40%|███████████▌                 | 2000/5000 [33:43<29:01,  1.72it/s]

Checkpoint sparad (231000)

Chunk 20:  50%|██████████████▍              | 2499/5000 [42:38<22:00,  1.89it/s]

231500 totalt klara...

Chunk 20:  50%|██████████████▌              | 2500/5000 [42:39<24:34,  1.70it/s]

Checkpoint sparad (231500)

Chunk 20:  60%|█████████████████▍           | 3000/5000 [50:55<18:45,  1.78it/s]

232000 totalt klara...
Checkpoint sparad (232000)

Chunk 20:  70%|████████████████████▎        | 3500/5000 [59:10<13:54,  1.80it/s]

232500 totalt klara...
Checkpoint sparad (232500)

Chunk 20:  80%|█████████████████████▌     | 3999/5000 [1:07:25<08:33,  1.95it/s]

233000 totalt klara...

Chunk 20:  80%|█████████████████████▌     | 4000/5000 [1:07:26<09:53,  1.68it/s]

Checkpoint sparad (233000)

Chunk 20:  90%|████████████████████████▎  | 4499/5000 [1:16:22<04:26,  1.88it/s]

233500 totalt klara...

Chunk 20:  90%|████████████████████████▎  | 4500/5000 [1:16:23<04:50,  1.72it/s]

Checkpoint sparad (233500)

Chunk 20: 100%|███████████████████████████| 5000/5000 [1:24:18<00:00,  1.01s/it]

234000 totalt klara...
Checkpoint sparad (234000)

Startar chunk 21 (5000 URL:er)

Chunk 21:  10%|██▉                           | 499/5000 [08:55<39:49,  1.88it/s]

234500 totalt klara...

Chunk 21:  10%|███                           | 500/5000 [08:56<44:28,  1.69it/s]

Checkpoint sparad (234500)

Chunk 21:  20%|█████▉                        | 999/5000 [17:11<33:54,  1.97it/s]

235000 totalt klara...

Chunk 21:  20%|█████▊                       | 1000/5000 [17:12<39:42,  1.68it/s]

Checkpoint sparad (235000)

Chunk 21:  30%|████████▋                    | 1499/5000 [25:27<29:56,  1.95it/s]

235500 totalt klara...

Chunk 21:  30%|████████▋                    | 1500/5000 [25:28<37:47,  1.54it/s]

Checkpoint sparad (235500)

Chunk 21:  40%|███████████▌                 | 1999/5000 [33:43<25:23,  1.97it/s]

236000 totalt klara...

Chunk 21:  40%|███████████▌                 | 2000/5000 [33:43<31:00,  1.61it/s]

Checkpoint sparad (236000)

Chunk 21:  50%|██████████████▍              | 2499/5000 [42:39<29:32,  1.41it/s]

236500 totalt klara...

Chunk 21:  50%|██████████████▌              | 2500/5000 [42:40<30:19,  1.37it/s]

Checkpoint sparad (236500)

Chunk 21:  60%|█████████████████▍           | 2999/5000 [50:55<17:02,  1.96it/s]

237000 totalt klara...

Chunk 21:  60%|█████████████████▍           | 3000/5000 [50:55<18:34,  1.79it/s]

Checkpoint sparad (237000)

Chunk 21:  70%|████████████████████▎        | 3499/5000 [59:11<13:01,  1.92it/s]

237500 totalt klara...

Chunk 21:  70%|████████████████████▎        | 3500/5000 [59:12<15:11,  1.65it/s]

Checkpoint sparad (237500)

Chunk 21:  80%|█████████████████████▌     | 3999/5000 [1:07:34<31:25,  1.88s/it]

238000 totalt klara...

Chunk 21:  80%|█████████████████████▌     | 4000/5000 [1:07:39<45:53,  2.75s/it]

Checkpoint sparad (238000)

Chunk 21:  90%|████████████████████████▎  | 4500/5000 [1:16:24<05:09,  1.62it/s]

238500 totalt klara...
Checkpoint sparad (238500)

Chunk 21: 100%|███████████████████████████| 5000/5000 [1:24:20<00:00,  1.01s/it]

239000 totalt klara...
Checkpoint sparad (239000)

Startar chunk 22 (5000 URL:er)

Chunk 22:  10%|██▉                           | 499/5000 [08:55<39:40,  1.89it/s]

239500 totalt klara...

Chunk 22:  10%|███                           | 500/5000 [08:56<44:44,  1.68it/s]

Checkpoint sparad (239500)

Chunk 22:  20%|█████▉                        | 999/5000 [17:11<34:03,  1.96it/s]

240000 totalt klara...

Chunk 22:  20%|█████▊                       | 1000/5000 [17:12<38:45,  1.72it/s]

Checkpoint sparad (240000)

Chunk 22:  30%|████████▋                    | 1499/5000 [25:27<29:38,  1.97it/s]

240500 totalt klara...

Chunk 22:  30%|████████▋                    | 1501/5000 [25:28<27:49,  2.10it/s]

Checkpoint sparad (240500)

Chunk 22:  40%|███████████▌                 | 2000/5000 [33:44<27:53,  1.79it/s]

241000 totalt klara...
Checkpoint sparad (241000)

Chunk 22:  50%|██████████████▍              | 2499/5000 [42:40<22:04,  1.89it/s]

241500 totalt klara...

Chunk 22:  50%|██████████████▌              | 2500/5000 [42:40<24:35,  1.69it/s]

Checkpoint sparad (241500)

Chunk 22:  60%|█████████████████▍           | 2999/5000 [50:55<17:01,  1.96it/s]

242000 totalt klara...

Chunk 22:  60%|█████████████████▍           | 3000/5000 [50:56<19:35,  1.70it/s]

Checkpoint sparad (242000)

Chunk 22:  70%|████████████████████▎        | 3499/5000 [59:11<12:37,  1.98it/s]

242500 totalt klara...

Chunk 22:  70%|████████████████████▎        | 3500/5000 [59:12<14:21,  1.74it/s]

Checkpoint sparad (242500)

Chunk 22:  80%|█████████████████████▌     | 3999/5000 [1:07:27<08:28,  1.97it/s]

243000 totalt klara...

Chunk 22:  80%|█████████████████████▌     | 4000/5000 [1:07:28<09:47,  1.70it/s]

Checkpoint sparad (243000)

Chunk 22:  90%|████████████████████████▎  | 4499/5000 [1:38:25<08:31,  1.02s/it]

243500 totalt klara...

Chunk 22:  90%|████████████████████████▎  | 4500/5000 [1:38:26<09:11,  1.10s/it]

Checkpoint sparad (243500)

Chunk 22: 100%|██████████████████████████▉| 4999/5000 [2:09:39<00:00,  1.98it/s]

244000 totalt klara...

Chunk 22: 100%|███████████████████████████| 5000/5000 [2:09:41<00:00,  1.56s/it]

Checkpoint sparad (244000)

Startar chunk 23 (5000 URL:er)

Chunk 24:  30%|████████▋                    | 1499/5000 [25:18<29:20,  1.99it/s]

250500 totalt klara...

Chunk 24:  30%|████████▋                    | 1500/5000 [25:20<40:04,  1.46it/s]

Checkpoint sparad (250500)

Chunk 31:  70%|████████████████████▎        | 3499/5000 [58:55<12:23,  2.02it/s]

287500 totalt klara...

Chunk 31:  70%|████████████████████▎        | 3500/5000 [58:57<20:10,  1.24it/s]

Checkpoint sparad (287500)

Chunk 31:  74%|████████████████████       | 3714/5000 [1:02:44<10:47,  1.99it/s]

Checkpoint sparad (291000)

Chunk 32:  50%|██████████████▍              | 2499/5000 [58:34<58:30,  1.40s/it]

291500 totalt klara...

Chunk 32:  50%|█████████████▌             | 2500/5000 [58:52<4:25:29,  6.37s/it]

Checkpoint sparad (291500)

Chunk 32: 100%|██████████████████████████▉| 4999/5000 [1:49:16<00:03,  3.71s/it]

294000 totalt klara...

Chunk 32: 100%|███████████████████████████| 5000/5000 [1:49:22<00:00,  1.31s/it]

Checkpoint sparad (294000)

Startar chunk 33 (5000 URL:er)

Chunk 33:  10%|██▊                         | 499/5000 [10:03<1:08:48,  1.09it/s]

294500 totalt klara...

Chunk 33:  10%|██▊                         | 501/5000 [10:15<3:39:49,  2.93s/it]

Checkpoint sparad (294500)

Chunk 33: 100%|█████████████████████████▉| 4999/5000 [1:52:48<05:34, 334.88s/it]

299000 totalt klara...

Chunk 33: 100%|███████████████████████████| 5000/5000 [2:03:24<00:00,  1.48s/it]

Checkpoint sparad (299000)

Startar chunk 34 (5000 URL:er)

Chunk 34: 100%|██████████████████████████▉| 4999/5000 [7:07:55<00:01,  1.45s/it]

304000 totalt klara...

Chunk 34: 100%|███████████████████████████| 5000/5000 [7:09:11<00:00,  5.15s/it]

Checkpoint sparad (304000)

Startar chunk 35 (5000 URL:er)

Chunk 35:  18%|████▉                       | 887/5000 [54:17<3:34:40,  3.13s/it]IOStream.flush timed out
Chunk 35:  19%|█████▏                      | 931/5000 [56:22<2:15:27,  2.00s/it]IOStream.flush timed out
Chunk 35:  19%|█████▍                      | 974/5000 [59:22<7:56:47,  7.11s/it]IOStream.flush timed out
Chunk 35:  20%|█████                     | 982/5000 [1:00:09<9:02:56,  8.11s/it]IOStream.flush timed out
Chunk 35:  20%|█████▏                    | 989/5000 [1:00:48<5:24:36,  4.86s/it]IOStream.flush timed out
Chunk 35:  20%|█████▏                    | 999/5000 [1:02:13<7:25:52,  6.69s/it]

305000 totalt klara...

Chunk 35:  20%|████▊                   | 1000/5000 [1:05:02<61:55:57, 55.74s/it]

Checkpoint sparad (305000)

Chunk 35:  21%|█████▎                   | 1055/5000 [1:09:32<3:58:26,  3.63s/it]IOStream.flush timed out
Chunk 35:  27%|██████▋                  | 1342/5000 [1:34:13<4:21:47,  4.29s/it]IOStream.flush timed out
Chunk 35:  29%|███████▏                 | 1431/5000 [1:42:21<5:14:54,  5.29s/it]IOStream.flush timed out
Chunk 35:  30%|███████▍                 | 1486/5000 [1:46:25<4:33:06,  4.66s/it]

In [ ]:
lang_stats = (
    df_riksdagen_wd
    .groupby("lang")
    .agg(
        total_links=("url", "count"),
        broken_links=("status", lambda s: (s == "dead").sum()),
        archived_links=("ia_status", lambda s: (s == "available").sum()),
    )
    .reset_index()
)

lang_stats["broken_pct"] = (
    100 * lang_stats["broken_links"] / lang_stats["total_links"]
).round(1)

lang_stats["broken_lost"] = (
    lang_stats["broken_links"] - lang_stats["archived_links"])

top10_langs = (
    lang_stats
    .sort_values("total_links", ascending=False)
    .head(10)
)
top10_langs[
    [
        "lang",
        "total_links",
        "broken_links",
        "broken_pct",
        "archived_links",
        "broken_lost",
    ]
]

In [ ]:
from urllib.parse import urlparse

df = df_riksdagen_wd.copy()

df["domain"] = df["url"].apply(
    lambda u: urlparse(u).netloc.lower() if pd.notna(u) else None
)
domain_stats = (
    df
    .groupby("domain")
    .agg(
        total_links=("url", "count"),
        broken_links=("status", lambda s: (s == "dead").sum()),
        error_links=("status", lambda s: (s == "error").sum()),
    )
    .reset_index()
)
domain_stats["broken_pct"] = (
    100 * domain_stats["broken_links"] / domain_stats["total_links"]
).round(1)

domain_stats["error_pct"] = (
    100 * domain_stats["error_links"] / domain_stats["total_links"]
).round(1)

In [ ]:
status_counts = df["status"].value_counts()

num_ok = int(status_counts.get("ok", 0))
num_dead = int(status_counts.get("dead", 0))
num_error = int(status_counts.get("error", 0))
num_total = len(df)

pct_ok = round(100 * num_ok / num_total, 1)
pct_dead = round(100 * num_dead / num_total, 1)
pct_error = round(100 * num_error / num_total, 1)

# Broken links: archived vs lost
num_dead_archived = df[
    (df["status"] == "dead") & (df["ia_status"] == "available")
].shape[0]

num_dead_lost = num_dead - num_dead_archived

In [ ]:
top_domains = (
    domain_stats[domain_stats["total_links"] >= 5]
    .sort_values("total_links", ascending=False)
    .head(10)
)
domain_stats_html = "<ul>"
for _, r in top_domains.iterrows():
    domain_stats_html += (
        f"<li><strong>{r['domain']}</strong>: "
        f"{r['broken_links']} / {r['total_links']} broken "
        f"({r['broken_pct']}%)</li>"
    )
domain_stats_html += "</ul>"

In [ ]:
from pathlib import Path
from datetime import date, datetime
from urllib.parse import quote
import pandas as pd


def save_sortable_html_df_riksdagen_wd(
    df,
    out_dir="resultsRiksdagenWD",
    domains=None,
    issue_url="https://github.com/salgo60/SCB-Wikidata/issues/64",
):
    out_dir = Path(out_dir)
    out_dir.mkdir(exist_ok=True)

    today = date.today().strftime("%Y_%m_%d")
    out_path = out_dir / f"links_riksdagen_v1_Wikidata_{today}.html"
 
    rerun_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

     # --- Förbered data ---
    df = df.copy()  
    status_counts = df["status"].value_counts()

    num_ok = int(status_counts.get("ok", 0))
    num_dead = int(status_counts.get("dead", 0))
    num_error = int(status_counts.get("error", 0))
    num_total = len(df)
    
    pct_ok = round(100 * num_ok / num_total, 1)
    pct_dead = round(100 * num_dead / num_total, 1)
    pct_error = round(100 * num_error / num_total, 1)
    
    # Broken links: archived vs lost
    num_dead_archived = df[
        (df["status"] == "dead") & (df["ia_status"] == "available")
    ].shape[0]
    
    num_dead_lost = num_dead - num_dead_archived

    domains = domains or []
    from urllib.parse import urlparse
    
    df["domain"] = df["url"].apply(
        lambda u: urlparse(u).netloc.lower() if pd.notna(u) else None
    )

    domain_stats = (
        df
        .groupby("domain")
        .agg(
            total_links=("url", "count"),
            broken_links=("status", lambda s: (s == "dead").sum()),
            error_links=("status", lambda s: (s == "error").sum()),
        )
        .reset_index()
    )
    
    domain_stats["broken_pct"] = (
        100 * domain_stats["broken_links"] / domain_stats["total_links"]
    ).round(1)
    
    domain_stats["error_pct"] = (
        100 * domain_stats["error_links"] / domain_stats["total_links"]
    ).round(1)
    
    domain_stats["problem_pct"] = (
        100 * (domain_stats["broken_links"] + domain_stats["error_links"])
        / domain_stats["total_links"]
    ).round(1)
    

    domain_stats_html = "<ul>"
    for _, r in top_domains.iterrows():
        domain_stats_html += (
            f"<li><strong>{r['domain']}</strong>: "
            f"{r['broken_links']} / {r['total_links']} broken "
            f"({r['broken_pct']}%)</li>"
        )
    domain_stats_html += "</ul>"

    domain_table_html = (
        domain_stats
        .head(20)
        .to_html(
            classes="pivot",
            border=0,
            index=False,
        )
    )
    lang_stats = (
    df
        .groupby("lang")
        .agg(
            total_links=("url", "count"),
            broken_links=("status", lambda s: (s == "dead").sum()),
            error_links=("status", lambda s: (s == "error").sum()),
            broken_archived=("ia_status", lambda s: (s == "available").sum()),
        )
        .reset_index()
    )
    
    lang_stats["broken_lost"] = (
        lang_stats["broken_links"] - lang_stats["broken_archived"]
    )
    
    lang_stats["broken_pct"] = (
        100 * lang_stats["broken_links"] / lang_stats["total_links"]
    ).round(1)
    
    lang_stats["problem_pct"] = (
        100 * (lang_stats["broken_links"] + lang_stats["error_links"])
        / lang_stats["total_links"]
    ).round(1)

    lang_stats = lang_stats.sort_values(
        "broken_links",
        ascending=False
    )
 
    lang_stats_display = lang_stats[
        [
            "lang",
            "total_links",
            "broken_links",
            "broken_archived",
            "broken_lost",
            "broken_pct",
            "problem_pct",
        ]
    ]

    lang_table_html = (
        lang_stats_display
        .head(15)
        .to_html(
            classes="pivot",
            border=0,
            index=False,
        )
    )

    STATUS_ICON = {
        "ok":    ("fa-circle-check", "#2e7d32", "OK"),
        "dead":  ("fa-circle-xmark", "#c62828", "Broken link"),
        "error": ("fa-triangle-exclamation", "#ef6c00", "Request error"),
    }
    
    if "status" in df.columns:
        def render_status(r):
            icon, color, label = STATUS_ICON.get(
                r["status"], ("fa-question-circle", "#757575", "Unknown")
            )
            reason = r.get("reason", "")
            return (
                f'<span class="status-icon" '
                f'data-status="{r["status"]}" '
                f'title="{label}: {reason}" '
                f'style="color:{color}; font-size:14px; cursor:pointer;">'
                f'<i class="fa-solid {icon}"></i>'
                f'</span>'
            )
        df.insert(
            0,
            "status_icon",
            df.apply(render_status, axis=1)
        )

        def render_ia_icon(r):
            if r.get("ia_status") == "available" and r.get("ia_url"):
                return (
                    f'<a href="{r["ia_url"]}" target="_blank" '
                    f'title="Archived copy (Internet Archive)">'
                    f'<i class="fa-solid fa-box-archive" '
                    f'style="color:#1565c0;"></i>'
                    f'</a>'
                )
            return ""
        
        df.insert(
            1,
            "archive",
            df.apply(render_ia_icon, axis=1)
        )


    # Wikipedia: ikon + titel (byggd från lang + page_title)
    if {"lang", "page_title"}.issubset(df.columns):
        df["page_title"] = df.apply(
            lambda r: (
                f'<a href="https://{r["lang"]}.wikipedia.org/wiki/{quote(str(r["page_title"]))}" '
                f'target="_blank" title="Wikipedia ({r["lang"]})">'
                f'<i class="fa-brands fa-wikipedia-w" style="margin-right:6px;"></i>'
                f'{r["page_title"]}</a>'
                if pd.notna(r["lang"]) and pd.notna(r["page_title"])
                else r["page_title"]
            ),
            axis=1,
        )

    # Externa länkar
    for col in ["Wikipedia-länk", "Extern länk", "url"]:
        if col in df.columns:
            df[col] = df[col].apply(
                lambda x: f'<a href="{x}" target="_blank">{x}</a>' if pd.notna(x) else ""
            )

    # --- HTML-tabell ---
    html_table = df.to_html(
        classes="pivot",
        border=0,
        escape=False,  # krävs för HTML-länkar
        index=False,
    )

    # --- CSS ---
    css = """
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 20px;
      }
      table.pivot {
        border-collapse: collapse;
        width: 100%;
        font-size: 12px;
      }
      table.pivot th, table.pivot td {
        border: 1px solid #999;
        padding: 6px 8px;
        text-align: left;
        vertical-align: top;
        white-space: normal;
      }
      table.pivot th {
        cursor: pointer;
        background: #f2f2f2;
      }
      table.pivot th:hover {
        background: #e2e2e2;
      }
      table.pivot thead th {
        position: sticky;
        top: 0;
        background: #f2f2f2;
        z-index: 2;
      }
      table.pivot th::after {
        content: "";
        float: right;
        opacity: 0.4;
      }
      table.pivot th.sorted-asc::after {
        content: " ▲";
      }
      table.pivot th.sorted-desc::after {
        content: " ▼";
      }
      /* Row coloring by status */
      table.pivot tr[data-status="dead"] {
         background-color: #fdecea;  /* light red */
      }
      table.pivot tr[data-status="dead"] td:nth-child(2) i {
          color: #1565c0;
        }

      table.pivot tr[data-status="error"] {
          background-color: #fff4e5;  /* light orange */
      }

      table.pivot td a {
        color: #0645ad;
        text-decoration: none;
      }
      table.pivot td a:hover {
        text-decoration: underline;
      }
      .meta {
        background: #f8f8f8;
        border: 1px solid #ccc;
        padding: 12px;
        margin-bottom: 20px;
        font-size: 13px;
      }
      .meta h2 {
        margin-top: 0;
      }
    </style>
    """

    # --- JavaScript (sortering) ---
    js = """
    <script>
    document.addEventListener('DOMContentLoaded', () => {
        // Propagate status from first cell to row
        document.querySelectorAll("table.pivot tbody tr").forEach(row => {
            const statusCell = row.querySelector(".status-icon");
            if (statusCell) {
                row.dataset.status = statusCell.dataset.status;
            }
        });
        let showOnlyBroken = false;

        document.querySelectorAll(".status-icon").forEach(icon => {
            icon.addEventListener("click", event => {
                event.stopPropagation(); // prevent column sort
                showOnlyBroken = !showOnlyBroken;
        
                document.querySelectorAll("table.pivot tbody tr").forEach(row => {
                    if (showOnlyBroken) {
                        row.style.display =
                            row.dataset.status === "dead" ? "" : "none";
                    } else {
                        row.style.display = "";
                    }
                });
            });
        });

        document.querySelectorAll("table.pivot th").forEach((header, colIndex) => {
            header.addEventListener("click", () => {
                const table = header.closest("table");
                const tbody = table.querySelector("tbody");
                const rows = Array.from(tbody.querySelectorAll("tr"));
                const asc = !header.classList.contains("sorted-asc");

                rows.sort((a, b) => {
                    const A = a.children[colIndex].innerText.trim();
                    const B = b.children[colIndex].innerText.trim();
                    const numA = parseFloat(A.replace(",", "."));
                    const numB = parseFloat(B.replace(",", "."));
                    if (!isNaN(numA) && !isNaN(numB)) {
                        return asc ? numA - numB : numB - numA;
                    }
                    return asc ? A.localeCompare(B) : B.localeCompare(A);
                });

                table.querySelectorAll("th").forEach(th =>
                    th.classList.remove("sorted-asc", "sorted-desc")
                );
                header.classList.add(asc ? "sorted-asc" : "sorted-desc");
                rows.forEach(row => tbody.appendChild(row));
            });
        });
    });
    </script>
    """
    status_counts = df["status"].value_counts()
    
    num_ok = status_counts.get("ok", 0)
    num_dead = status_counts.get("dead", 0)
    num_error = status_counts.get("error", 0)
    num_total = len(df)

    # --- Metadata ---
    meta_html = f"""
    <div class="meta">
      <h2>Summary</h2>
    
      <p><strong>Rerun:</strong> {rerun_ts}</p>
      <p><strong>Script:</strong>
         <a href="{SCRIPT_URL}" target="_blank">{SCRIPT_NAME}</a>
      </p>
    
      <p>
        <strong>Links checked:</strong> {num_total}<br>
        <strong style="color:#2e7d32;">OK:</strong> {num_ok} ({pct_ok}%)<br>
        <strong style="color:#c62828;">Broken:</strong> {num_dead} ({pct_dead}%)<br>
        &nbsp;&nbsp;↳ Archived: {num_dead_archived}<br>
        &nbsp;&nbsp;↳ Lost: {num_dead_lost}<br>
        <strong style="color:#ef6c00;">Errors:</strong> {num_error} ({pct_error}%)
      </p>
      <p><strong>Issue:</strong>
         <a href="{issue_url}" target="_blank">{issue_url.split("/")[-1]}</a>
      </p>
    
      <p><strong>Datakällor:</strong><br>
         Wikidata<br>
         MediaWiki API – exturlusage
      </p>
    
      <h2>Domains with broken links</h2>
      <p>Top domains ranked by broken-link impact.</p>
      {domain_table_html}
    </div>
    """


    # --- Slutlig HTML ---
    title_text = "riksdagen.se links in Wikidata" 
    if WikidataInclude: 
        title_text = " and Wikidata"
    html = f"""
    <html>
    <head>
      <meta charset="utf-8">
      <title>{title_text}/title>
      <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
      {css}
    </head>
    <body>
      <h1>Wikidata → Riksdagen v1</h1>
      {meta_html}
      <p>Sorterbar tabell. Klicka på kolumnrubriker för sortering.</p>
      {html_table}
      {js}
      <h2>Broken-link summary by Wikipedia language</h2>
     <p>
       Languages ranked by broken-link impact (broken + error links).
     </p>
    {lang_table_html}
    </body>
    </html>
    """

    out_path.write_text(html, encoding="utf-8")
    print(f"✅ HTML skapad: {out_path}")

In [ ]:
 # End timer and calculate duration
end_time = time.time()
elapsed_time = end_time - start_time# Bygg audit-lager för den här etappen

# Print current date and total time
print("Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
minutes, seconds = divmod(elapsed_time, 60)
print("Total time elapsed: {:02.0f} minutes {:05.2f} seconds".format(minutes, seconds))