* Notebook [riksdagen_64_wikidata.ipynb](https://github.com/salgo60/SCB-Wikidata/blob/main/notebook/riksdagen_64_wikidata.ipynb) 
* [#64](https://github.com/salgo60/SCB-Wikidata/issues/64)
* result   
   * [html](https://salgo60.github.io/SCB-Wikidata/notebook/resultsRiksdagenWD/links_RiksdagenWikidata_v1_2026_02_08.html) 
   * [csv](https://salgo60.github.io/SCB-Wikidata/notebook/resultsRiksdagenWD/links_RiksdagenWikidata_v1_2026_02_08.csv)

In [1]:
import time

from datetime import datetime

now = datetime.now()
timestamp = now.timestamp()

start_time = time.time()
print("Start:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Start: 2026-02-16 01:31:25

In [2]:
WikidataInclude = False
SCRIPT_NAME = "riksdagen_64_wikidata.ipynb"
SCRIPT_URL = (
    "https://github.com/salgo60/SCB-Wikidata/"
    "blob/master/notebook/riksdagen_64_wikidata.ipynb"
)

In [3]:
import os

# Get the current working directory
current_directory = os.getcwd()
print("Current Working Directory:", current_directory)

Current Working Directory: /Users/salgo/Documents/GitHub/SCB-Wikidata/notebook

In [4]:
import requests

SESSION = requests.Session()
SESSION.headers.update({
    "User-Agent": "Mozilla/5.0 (compatible; URL-checker/1.0) salgo60@msn.com"
})

In [5]:
def read_domains(file_path):
    print(f"[DEBUG] Reading domains from: {file_path}")
    df = pd.read_csv(file_path, header=0)   # <- skip header row
    domains_list = df.iloc[:, 0].dropna().unique().tolist()
    print(f"[DEBUG] Found {len(domains_list)} domains.")
    return domains_list

In [6]:
import requests

def fetch_sitematrix_df():
    url = "https://meta.wikimedia.org/w/api.php"
    params = {
        "action": "sitematrix",
        "format": "json"
    }
    headers = {
        "User-Agent": "salgo60-language-fetcher/1.0 (salgo60@msn.com)"
    }

    print("[DEBUG] Fetching sitematrix…")
    r = requests.get(url, params=params, headers=headers)
    r.raise_for_status()

    if "application/json" not in r.headers.get("Content-Type", ""):
        raise ValueError("Server returned non-JSON response")

    data = r.json()["sitematrix"]

    rows = []

    # --- language-specific sites ---
    for key, lang_block in data.items():
        if not key.isdigit():
            continue  # skip "count", "specials"

        lang_code = lang_block.get("code")
        lang_name = lang_block.get("name")

        for site in lang_block.get("site", []):
            rows.append({
                "lang_code": lang_code,
                "lang_name": lang_name,
                "project": site.get("project"),
                "url": site.get("url"),
                "dbname": site.get("dbname"),
                "site_name": site.get("sitename"),
                "closed": site.get("closed", False)
            })

    # --- special wikis (Wikidata, Commons, Meta, etc.) ---
    for site in data.get("specials", []):
        rows.append({
            "lang_code": "special",
            "lang_name": "special",
            "project": site.get("project"),
            "url": site.get("url"),
            "dbname": site.get("dbname"),
            "site_name": site.get("sitename"),
            "closed": site.get("closed", False)
        })

    return pd.DataFrame(rows)

In [7]:
import requests
import pandas as pd


HEADERS = {
    "User-Agent": "salgo60-language-fetcher/2.0 (https://github.com/salgo60) salgo60@msn.com"
}


df_lang_fetch = fetch_sitematrix_df()
df_lang_fetch["closed"] = df_lang_fetch["closed"].fillna(False).astype(bool)

df_lang_wikipedia = df_lang_fetch[
    (df_lang_fetch["site_name"] == "Wikipedia") &
    (
        (df_lang_fetch["lang_name"].str.lower() != "special") |
        (df_lang_fetch["dbname"] == "wikidatawiki")
    )
]  

#df_lang_wikipedia.to_csv("test.csv")
df_lang_wikipedia.info()

[DEBUG] Fetching sitematrix…
<class 'pandas.core.frame.DataFrame'>
Index: 186 entries, 0 to 1047
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   lang_code  186 non-null    object
 1   lang_name  185 non-null    object
 2   project    0 non-null      object
 3   url        186 non-null    object
 4   dbname     186 non-null    object
 5   site_name  186 non-null    object
 6   closed     186 non-null    bool
dtypes: bool(1), object(6)
memory usage: 10.4+ KB

In [8]:
df_lang_wikipedia

,lang_code,lang_name,project,url,dbname,site_name,closed
0,aa,Qafár af,None,https://aa.wikipedia.org,aawiki,Wikipedia,False
5,ace,Acèh,None,https://ace.wikipedia.org,acewiki,Wikipedia,False
7,af,Afrikaans,None,https://af.wikipedia.org,afwiki,Wikipedia,False
11,ak,None,None,https://ak.wikipedia.org,akwiki,Wikipedia,False
18,ami,Pangcah,None,https://ami.wikipedia.org,amiwiki,Wikipedia,False
...,...,...,...,...,...,...,...
924,za,Vahcuengh,None,https://za.wikipedia.org,zawiki,Wikipedia,False
928,zea,Zeêuws,None,https://zea.wikipedia.org,zeawiki,Wikipedia,False
931,zh,中文,None,https://zh.wikipedia.org,zhwiki,Wikipedia,False
939,zu,isiZulu,None,https://zu.wikipedia.org,zuwiki,Wikipedia,False
1047,special,special,None,https://www.wikidata.org,wikidatawiki,Wikipedia,False

### Bara köra Wikidata

In [9]:
df_wd = df_lang_wikipedia[df_lang_wikipedia["lang_code"] == "special"]

In [10]:
df_wd

,lang_code,lang_name,project,url,dbname,site_name,closed
1047,special,special,None,https://www.wikidata.org,wikidatawiki,Wikipedia,False

In [11]:
def read_domains(file_path):
    print(f"[DEBUG] Reading domains from: {file_path}")
    df = pd.read_csv(file_path, header=0)   # <- skip header row
    domains_list = df.iloc[:, 0].dropna().unique().tolist()
    print(f"[DEBUG] Found {len(domains_list)} domains.")
    return domains_list

In [12]:
import os
import time
import random
import requests
import pandas as pd
from urllib.parse import urlparse
from tqdm.notebook import tqdm
file_path_domain = "sources/domains_riksdagen.csv"
domains = read_domains(file_path_domain)
print(domains)

[DEBUG] Reading domains from: sources/domains_riksdagen.csv
[DEBUG] Found 1 domains.
['riksdagen.se']

In [13]:
import requests

def fetch_sitematrix_df():
    url = "https://meta.wikimedia.org/w/api.php"
    params = {
        "action": "sitematrix",
        "format": "json"
    }
    headers = {
        "User-Agent": "salgo60-language-fetcher/1.0 (salgo60@msn.com)"
    }

    print("[DEBUG] Fetching sitematrix…")
    r = requests.get(url, params=params, headers=headers)
    r.raise_for_status()

    if "application/json" not in r.headers.get("Content-Type", ""):
        raise ValueError("Server returned non-JSON response")

    data = r.json()["sitematrix"]

    rows = []


    # --- special wikis (Wikidata, Commons, Meta, etc.) ---
    for site in data.get("specials", []):
        print(site)
        rows.append({
            "lang_code": "special",
            "lang_name": "special",
            "project": site.get("project"),
            "url": site.get("url"),
            "dbname": site.get("dbname"),
            "site_name": site.get("sitename"),
            "closed": site.get("closed", False)
        })

    return pd.DataFrame(rows)

In [14]:

df_wd.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 1047 to 1047
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   lang_code  1 non-null      object
 1   lang_name  1 non-null      object
 2   project    0 non-null      object
 3   url        1 non-null      object
 4   dbname     1 non-null      object
 5   site_name  1 non-null      object
 6   closed     1 non-null      bool
dtypes: bool(1), object(6)
memory usage: 57.0+ bytes

In [15]:
df_wd

,lang_code,lang_name,project,url,dbname,site_name,closed
1047,special,special,None,https://www.wikidata.org,wikidatawiki,Wikipedia,False

In [16]:
def resolve_api_base(lang):
    if lang == "special":
        # Wikidata (only valid "special" case in your pipeline)
        return "https://www.wikidata.org/w/api.php"

    return f"https://{lang}.wikipedia.org/w/api.php"

In [17]:
def request_timeout(lang):
    return 100 if lang == "special" else 10

In [18]:
import os

CHECKPOINT_FILE = "checkpoint_riksdagen_wd_links.parquet"

def load_checkpoint():
    if os.path.exists(CHECKPOINT_FILE):
        df_cp = pd.read_parquet(CHECKPOINT_FILE)
        print(f"Checkpoint hittad: {len(df_cp)} rader")
        return df_cp
    return pd.DataFrame()

In [19]:
# -----------------------------------------------------------
# Fetch exturlusage entries for one lang/domain
# -----------------------------------------------------------
def fetch_exturlusage(lang, domain):
    #base = f"https://{lang}.wikipedia.org/w/api.php"
    base = resolve_api_base(lang)
    params = {
        "action": "query",
        "format": "json",
        "list": "exturlusage",
        "euquery": domain,
        "eulimit": "max"
    }
    while True:
        #r = session.get(base, params=params, timeout=10)
        r = session.get(base, params=params, timeout=request_timeout(lang))        
        try:
            data = r.json()
        except ValueError:
            print(f"[WARN] {lang}: JSON decode failed")
            break

        for item in data.get("query", {}).get("exturlusage", []):
            yield {
                "lang": lang,
                "page_title": item.get("title"),
                "url": item.get("url"),
                "wiki_link": f"https://{lang}.wikipedia.org/wiki/{item.get('title').replace(' ', '_')}"
            }

        if "continue" not in data:
            break
        params.update(data["continue"])
        time.sleep(0.3)

In [20]:
df_wd

,lang_code,lang_name,project,url,dbname,site_name,closed
1047,special,special,None,https://www.wikidata.org,wikidatawiki,Wikipedia,False

In [21]:
domains

['riksdagen.se']

In [22]:
UseWDCache = True  # True = använd cache, False = hämta från WD
CACHE_FILE = "riksdagen_wd_cache.json"

In [23]:
import json
import os

if os.path.exists(CACHE_FILE):
    with open(CACHE_FILE, "r", encoding="utf-8") as f:
        cache = json.load(f)
else:
    cache = {}

In [24]:
def fetch_with_cache(lang, domains):
    global cache

    key = f"{lang}|{'|'.join(domains)}"

    # --- Läs från cache ---
    if UseWDCache:
        if key in cache:
            print("CACHE HIT:", key)
            return cache[key]
        else:
            print("CACHE MISS (UseWDCache=True):", key)
            return []

    # --- Hämta från WD ---
    data = list(fetch_exturlusage(lang, domains))

    cache[key] = data

    # skriv till fil direkt (säkert vid långa körningar)
    with open(CACHE_FILE, "w", encoding="utf-8") as f:
        json.dump(cache, f)

    return data

In [25]:

# -------------------------
# Session & helpers
# -------------------------
session = requests.Session()
session.headers.update({"User-Agent": "SCB-LinkAudit/1.0 salgo60@msn.com"})


print("Antal Språk:",len(df_wd))

results = []



results = []

for _, row in df_wd.iterrows():
    lang = row["lang_code"]
    url  = row["url"]
    lang_name = row["lang_name"]

    before = len(results)

    print(lang, url, lang_name, domains)

    entries = fetch_with_cache(lang, domains)
    results.extend(entries)

    after = len(results)
    print(lang, url, lang_name, "-", after-before)

Antal Språk: 1
special https://www.wikidata.org special ['riksdagen.se']
CACHE HIT: special|riksdagen.se
special https://www.wikidata.org special - 617191

In [26]:
df_riksdagen_wd = pd.DataFrame(results)
df_riksdagen_wd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 617191 entries, 0 to 617190
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   lang        617191 non-null  object
 1   page_title  617191 non-null  object
 2   url         617191 non-null  object
 3   wiki_link   617191 non-null  object
dtypes: object(4)
memory usage: 18.8+ MB

In [27]:
import pandas as pd

# --- Stats ---
total_links = len(df_riksdagen_wd)
total_unique_links = df_riksdagen_wd['url'].nunique()
num_languages = df_riksdagen_wd['lang'].nunique()
langs_sorted = df_riksdagen_wd['lang'].value_counts()

print("Total links:", total_links)
print("Total unique links:", total_unique_links)
print("Wikidata")

Total links: 617191
Total unique links: 614687
Wikidata

### Check url

In [28]:
import requests 
from requests.exceptions import RequestException 
from concurrent.futures import ThreadPoolExecutor, as_completed 
from tqdm import tqdm 
import pandas as pd 
import time  
import threading

In [29]:
MAX_WORKERS = 64              # För IO-bound scraping kan du ofta köra 32–128 workers
MAX_WORKERS = min(128, os.cpu_count()*10)
REQUEST_TIMEOUT = 15

RATE_LIMIT_PER_SEC = 2       # max requests/sek totalt
BACKOFF_FACTOR = 2
MAX_RETRIES = 3

CHECKPOINT_EVERY = 500
CHUNK_SIZE = 5000

CHECKPOINT_FILE = "checkpoint_riksdagen_wikidata.parquet"

In [30]:
import threading
import time

rate_lock = threading.Lock()
last_request_time = 0

def wait_for_rate_limit():
    global last_request_time
    
    with rate_lock:
        now = time.time()
        wait = 1 / RATE_LIMIT_PER_SEC - (now - last_request_time)
        if wait > 0:
            time.sleep(wait)
        last_request_time = time.time()

In [31]:
def request_with_retry(method, url, session, **kwargs):
    delay = 1
    
    for attempt in range(MAX_RETRIES):
        try:
            wait_for_rate_limit()
            return session.request(method, url, **kwargs)
        
        except RequestException:
            if attempt == MAX_RETRIES - 1:
                raise
            time.sleep(delay)
            delay *= BACKOFF_FACTOR

In [32]:
def check_url(url: str) -> dict:
    session = get_session()

    try:
        r = request_with_retry(
            "HEAD",
            url,
            session,
            allow_redirects=False,
            timeout=REQUEST_TIMEOUT,
        )
    except RequestException as e:
        return {"url": url, "status": "error", "reason": str(e)}

    final_url = r.url

    if r.status_code >= 400:
        return {"url": url, "status": "dead", "reason": f"HTTP {r.status_code}"}

    if norm(final_url) == norm(ROOT_CANONICAL) and norm(url) != norm(final_url):
        return {"url": url, "status": "dead", "reason": "redirect_to_root"}

    try:
        r = request_with_retry(
            "GET",
            final_url,
            session,
            allow_redirects=True,
            timeout=REQUEST_TIMEOUT,
        )
    except RequestException as e:
        return {"url": url, "status": "error", "reason": str(e)}

    if looks_like_soft_404(r):
        return {"url": url, "status": "dead", "reason": "soft_404"}

    return {"url": url, "status": "ok"}

In [33]:
import os

def load_checkpoint():
    if os.path.exists(CHECKPOINT_FILE):
        return pd.read_parquet(CHECKPOINT_FILE)
    return pd.DataFrame()

In [34]:
from itertools import islice

def chunks(iterable, size):
    it = iter(iterable)
    while chunk := list(islice(it, size)):
        yield chunk

In [35]:
# ========================== # Internet Archive # ========================== 
def check_internet_archive(url: str) -> str | None: 
    session = get_session() 
    api = "https://archive.org/wayback/available" 
    
    try: 
        r = session.get( api, 
                        params={"url": url}, 
                        timeout=10, ) 
        data = r.json() 
    except Exception: 
        return None 
    snap = data.get("archived_snapshots", {}).get("closest") 
    if snap and snap.get("available"): 
        return snap.get("url") 
    return None

In [36]:


def is_worth_checking(url: str) -> bool: 
    if not url.startswith("http"):
        return False 
    if "riksdagen.se" not in url: 
        return False 
    return True

In [37]:
# ========================== # Worker # ========================== 
def process_url(url: str) -> dict: 
    result = check_url(url) 
    if result["status"] == "dead": 
        ia_url = check_internet_archive(url) 
        result["ia_url"] = ia_url 
        result["ia_status"] = "available" if ia_url else "missing" 
    else: 
        result["ia_url"] = None 
        result["ia_status"] = "skipped" 
    return result

In [38]:
def run(df):

    # -------------------------
    # 1. Bygg unik URL-lista
    # -------------------------
    urls_all = (
        df["url"]
            .dropna()
            .astype(str)
            .unique()
    )

    urls_all = [u for u in urls_all if is_worth_checking(u)]

    # -------------------------
    # 2. Ladda och städa checkpoint
    # -------------------------
    cp = load_checkpoint()

    if not cp.empty:
        cp = (
            cp
                .sort_index()
                .drop_duplicates(subset="url", keep="last")
                .reset_index(drop=True)
        )

    done = set(cp["url"]) if not cp.empty else set()

    urls_remaining = [u for u in urls_all if u not in done]

    print("Totalt:", len(urls_all))
    print("Redan klara:", len(done))
    print("Kvar:", len(urls_remaining))

    if not urls_remaining:
        print("Inget att göra — allt redan processat.")
        return cp

    # -------------------------
    # 3. Processa i chunkar
    # -------------------------
    for chunk_idx, chunk in enumerate(chunks(urls_remaining, CHUNK_SIZE), 1):

        print(f"\nStartar chunk {chunk_idx} ({len(chunk)} URL:er)")

        results_chunk = []

        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
            futures = {ex.submit(process_url, u): u for u in chunk}

            for f in tqdm(
                as_completed(futures),
                total=len(futures),
                desc=f"Chunk {chunk_idx}",
            ):
                res = f.result()
                url = res["url"]

                # SKYDD 1: dubbelkörningsskydd
                if url in done:
                    continue

                results_chunk.append(res)
                done.add(url)

        # -------------------------
        # 4. Spara chunk direkt
        # -------------------------
        if results_chunk:

            df_chunk = pd.DataFrame(results_chunk)

            if os.path.exists(CHECKPOINT_FILE):
                old = pd.read_parquet(CHECKPOINT_FILE)
                df_new = (
                    pd.concat([old, df_chunk])
                        .drop_duplicates(subset="url", keep="last")
                )
            else:
                df_new = df_chunk

            tmp = CHECKPOINT_FILE + ".tmp"
            df_new.to_parquet(tmp)
            os.replace(tmp, CHECKPOINT_FILE)

            print(f"Checkpoint uppdaterad ({len(df_new)} unika)")

    # -------------------------
    # 5. Slutresultat
    # -------------------------
    final = pd.read_parquet(CHECKPOINT_FILE)
    final = final.drop_duplicates(subset="url", keep="last")

    print("\nKLAR.")
    print("Totalt unika:", len(final))

    return final

In [39]:

import requests
import threading

USER_AGENT = "LinkChecker/1.0 salgo60@msn.com"

thread_local = threading.local()

def get_session():
    if not hasattr(thread_local, "session"):
        s = requests.Session()
        s.headers.update({"User-Agent": USER_AGENT})
        thread_local.session = s
    return thread_local.session


def norm(u: str) -> str:
    return u.rstrip("/").lower()


def is_worth_checking(url: str) -> bool:
    return url.startswith("http") and "riksdagen.se" in url

In [40]:
def looks_like_soft_404(response) -> bool:
    text = (response.text or "").lower()

    for phrase in SOFT_404_PHRASES:
        if phrase in text:
            return True

    if "<title>" in text:
        title = text.split("<title>", 1)[1].split("</title>", 1)[0]
        if "404" in title.lower():
            return True
        if "sidan finns inte" in title.lower():
            return True

    return False

SOFT_404_PHRASES = [
    "sidan kan inte hittas",
    "sidan tagits bort",
    "felaktig adress",
    "kontakta registrator",
    "sidan finns inte",
    "den här sidan kan inte visas",
    "Hoppsan! Vi kunde tyvärr inte hitta sidan"
]

USER_AGENT = "LinkChecker/1.0 (research; salgo60@msn.com)"

In [41]:
ROOT_CANONICAL = "https://www.riksdagen.se"

In [42]:
df_result = run(df_riksdagen_wd)

from datetime import date
import os

# Sätt datum
today = date.today().strftime("%Y_%m_%d")

# Se till att katalogen finns
os.makedirs("resultsRiksdagenWD", exist_ok=True)

# Bygg filnamn
outfile = f"resultsRiksdagenWD/links_Riksdagen_v1_Wikidata_{today}.csv"
    
# Exportera
df_riksdagen_wd.to_csv(outfile, index=False, encoding="utf-8")

print(f"[OK] Exported {len(df_riksdagen_wd)} rows to {outfile}")

Totalt: 614687
Redan klara: 317500
Kvar: 297187
MAX_WORKERS: 80

Startar chunk 1 (5000 URL:er)

Startar chunk 1 (5000 URL:er)

Chunk 1:  10%|██▉                          | 499/5000 [23:07<3:34:35,  2.86s/it]

318000 totalt klara...

Chunk 1:  10%|██▉                          | 500/5000 [23:15<5:33:00,  4.44s/it]

Checkpoint sparad (318000)

Chunk 1:  40%|███████████▏                | 1999/5000 [1:16:12<57:42,  1.15s/it]

319500 totalt klara...

Chunk 1:  40%|███████████▏                | 2000/5000 [1:16:14<59:28,  1.19s/it]

Checkpoint sparad (319500)

Chunk 1:  50%|████████████▉             | 2499/5000 [1:33:52<2:27:33,  3.54s/it]

320000 totalt klara...

Chunk 1:  50%|█████████████             | 2500/5000 [1:33:54<2:09:52,  3.12s/it]

Checkpoint sparad (320000)

Chunk 1:  90%|█████████████████████████▏  | 4499/5000 [2:42:54<18:18,  2.19s/it]

322000 totalt klara...

Chunk 1:  90%|█████████████████████████▏  | 4501/5000 [2:42:58<16:46,  2.02s/it]

Checkpoint sparad (322000)

Chunk 1: 100%|███████████████████████████▉| 4999/5000 [2:59:04<00:01,  1.27s/it]

322500 totalt klara...

Chunk 1: 100%|████████████████████████████| 5000/5000 [3:00:46<00:00,  2.17s/it]

Checkpoint sparad (322500)

Startar chunk 2 (5000 URL:er)

Chunk 2:  10%|███                            | 499/5000 [09:10<54:49,  1.37it/s]

323000 totalt klara...

Chunk 2:  10%|██▉                          | 500/5000 [09:13<1:41:39,  1.36s/it]

Checkpoint sparad (323000)

Chunk 2:  70%|███████████████████▌        | 3499/5000 [1:01:30<27:56,  1.12s/it]

326000 totalt klara...

Chunk 2:  70%|███████████████████▌        | 3500/5000 [1:01:31<26:54,  1.08s/it]

Checkpoint sparad (326000)

Chunk 2:  80%|██████████████████████▍     | 3999/5000 [1:10:16<17:47,  1.07s/it]

326500 totalt klara...

Chunk 2:  80%|██████████████████████▍     | 4000/5000 [1:10:17<18:31,  1.11s/it]

Checkpoint sparad (326500)

Chunk 2:  90%|█████████████████████████▏  | 4499/5000 [1:18:50<09:03,  1.08s/it]

327000 totalt klara...

Chunk 2:  90%|█████████████████████████▏  | 4500/5000 [1:18:52<11:08,  1.34s/it]

Checkpoint sparad (327000)

Chunk 2: 100%|███████████████████████████▉| 4999/5000 [1:27:27<00:00,  1.95it/s]

327500 totalt klara...

Chunk 2: 100%|████████████████████████████| 5000/5000 [1:27:28<00:00,  1.05s/it]

Checkpoint sparad (327500)

Startar chunk 3 (5000 URL:er)

Chunk 3:  10%|███                            | 499/5000 [08:56<47:25,  1.58it/s]

328000 totalt klara...

Chunk 3:  10%|███                            | 500/5000 [08:56<42:43,  1.76it/s]

Checkpoint sparad (328000)

Chunk 3:  20%|██████▏                        | 999/5000 [17:14<37:00,  1.80it/s]

328500 totalt klara...

Chunk 3:  20%|██████                        | 1000/5000 [17:14<34:51,  1.91it/s]

Checkpoint sparad (328500)

Chunk 3:  30%|████████▉                     | 1499/5000 [25:32<34:36,  1.69it/s]

329000 totalt klara...

Chunk 3:  30%|█████████                     | 1501/5000 [25:32<25:16,  2.31it/s]

Checkpoint sparad (329000)

Chunk 3:  40%|███████████▉                  | 1999/5000 [33:49<38:17,  1.31it/s]

329500 totalt klara...

Chunk 3:  40%|███████████▏                | 2000/5000 [33:53<1:16:04,  1.52s/it]

Checkpoint sparad (329500)

Chunk 3:  50%|██████████████▉               | 2499/5000 [42:46<21:58,  1.90it/s]

330000 totalt klara...

Chunk 3:  50%|███████████████               | 2500/5000 [42:47<25:13,  1.65it/s]

Checkpoint sparad (330000)

Chunk 3:  60%|█████████████████▉            | 2999/5000 [51:04<16:49,  1.98it/s]

330500 totalt klara...

Chunk 3:  60%|██████████████████            | 3000/5000 [51:04<19:12,  1.74it/s]

Checkpoint sparad (330500)

Chunk 3:  70%|████████████████████▉         | 3499/5000 [59:22<12:37,  1.98it/s]

331000 totalt klara...

Chunk 3:  70%|█████████████████████         | 3501/5000 [59:23<11:54,  2.10it/s]

Checkpoint sparad (331000)

Chunk 3:  80%|██████████████████████▍     | 3999/5000 [1:07:43<24:15,  1.45s/it]

331500 totalt klara...

Chunk 3:  80%|████████████████████▊     | 4000/5000 [1:08:03<1:54:43,  6.88s/it]

Checkpoint sparad (331500)

Chunk 3:  90%|█████████████████████████▏  | 4499/5000 [1:16:37<04:25,  1.89it/s]

332000 totalt klara...

Chunk 3:  90%|█████████████████████████▏  | 4501/5000 [1:16:38<04:03,  2.05it/s]

Checkpoint sparad (332000)

Chunk 3: 100%|███████████████████████████▉| 4999/5000 [1:24:35<00:00,  1.96it/s]

332500 totalt klara...

Chunk 3: 100%|████████████████████████████| 5000/5000 [1:24:36<00:00,  1.02s/it]

Checkpoint sparad (332500)

Startar chunk 4 (5000 URL:er)

Chunk 4:  10%|███                            | 499/5000 [08:57<41:14,  1.82it/s]

333000 totalt klara...

Chunk 4:  10%|███                            | 500/5000 [08:58<44:48,  1.67it/s]

Checkpoint sparad (333000)

Chunk 4:  20%|██████▏                        | 999/5000 [17:14<35:14,  1.89it/s]

333500 totalt klara...

Chunk 4:  20%|██████                        | 1000/5000 [17:15<38:33,  1.73it/s]

Checkpoint sparad (333500)

Chunk 4:  30%|████████▉                     | 1499/5000 [25:32<30:07,  1.94it/s]

334000 totalt klara...

Chunk 4:  30%|█████████                     | 1500/5000 [25:33<33:24,  1.75it/s]

Checkpoint sparad (334000)

Chunk 4:  40%|████████████                  | 2000/5000 [33:50<28:18,  1.77it/s]

334500 totalt klara...
Checkpoint sparad (334500)

Chunk 4:  50%|██████████████▉               | 2498/5000 [42:51<31:45,  1.31it/s]

335000 totalt klara...

Chunk 4:  50%|███████████████               | 2500/5000 [42:51<23:08,  1.80it/s]

Checkpoint sparad (335000)

Chunk 4:  60%|██████████████████            | 3000/5000 [51:13<20:18,  1.64it/s]

335500 totalt klara...
Checkpoint sparad (335500)

Chunk 4:  70%|████████████████████▉         | 3499/5000 [59:35<09:07,  2.74it/s]

336000 totalt klara...

Chunk 4:  70%|█████████████████████         | 3500/5000 [59:35<08:23,  2.98it/s]

Checkpoint sparad (336000)

Chunk 4:  80%|██████████████████████▍     | 3999/5000 [1:08:16<55:36,  3.33s/it]

336500 totalt klara...

Chunk 4:  80%|██████████████████████▍     | 4000/5000 [1:08:17<45:12,  2.71s/it]

Checkpoint sparad (336500)

Chunk 4:  90%|█████████████████████████▏  | 4499/5000 [1:17:00<04:44,  1.76it/s]

337000 totalt klara...

Chunk 4:  90%|█████████████████████████▏  | 4500/5000 [1:17:01<06:25,  1.30it/s]

Checkpoint sparad (337000)

Chunk 4: 100%|███████████████████████████▉| 4999/5000 [1:25:03<00:00,  1.71it/s]

337500 totalt klara...

Chunk 4: 100%|████████████████████████████| 5000/5000 [1:25:04<00:00,  1.02s/it]

Checkpoint sparad (337500)

Startar chunk 5 (5000 URL:er)

Chunk 5:  10%|███                            | 498/5000 [08:59<42:30,  1.77it/s]

338000 totalt klara...

Chunk 5:  10%|███                            | 500/5000 [09:01<51:12,  1.46it/s]

Checkpoint sparad (338000)

Chunk 5:  20%|██████▏                        | 998/5000 [17:21<24:48,  2.69it/s]

338500 totalt klara...

Chunk 5:  20%|██████                        | 1000/5000 [17:22<18:21,  3.63it/s]

Checkpoint sparad (338500)

Chunk 5:  30%|████████▉                     | 1499/5000 [25:48<32:02,  1.82it/s]

339000 totalt klara...

Chunk 5:  30%|█████████                     | 1500/5000 [25:48<33:47,  1.73it/s]

Checkpoint sparad (339000)

Chunk 5:  40%|███████████▏                | 2000/5000 [34:25<2:03:22,  2.47s/it]

339500 totalt klara...
Checkpoint sparad (339500)

Chunk 5:  50%|██████████████▉               | 2499/5000 [43:07<35:45,  1.17it/s]

340000 totalt klara...

Chunk 5:  50%|███████████████               | 2500/5000 [43:10<52:07,  1.25s/it]

Checkpoint sparad (340000)

Chunk 5:  60%|█████████████████▉            | 2999/5000 [51:26<21:05,  1.58it/s]

340500 totalt klara...

Chunk 5:  60%|██████████████████            | 3001/5000 [51:27<14:15,  2.34it/s]

Checkpoint sparad (340500)

Chunk 5:  70%|████████████████████▉         | 3499/5000 [59:52<23:31,  1.06it/s]

341000 totalt klara...

Chunk 5:  70%|█████████████████████         | 3500/5000 [59:54<27:53,  1.12s/it]

Checkpoint sparad (341000)

Chunk 5:  80%|██████████████████████▍     | 3999/5000 [1:08:19<21:38,  1.30s/it]

341500 totalt klara...

Chunk 5:  80%|████████████████████▊     | 4000/5000 [1:08:30<1:09:41,  4.18s/it]

Checkpoint sparad (341500)

Chunk 10:  40%|███████████▌                 | 1999/5000 [34:12<25:55,  1.93it/s]

364500 totalt klara...

Chunk 10:  40%|███████████▌                 | 2000/5000 [34:13<30:08,  1.66it/s]

Checkpoint sparad (364500)

Chunk 11:  50%|██████████████▍              | 2499/5000 [42:26<19:58,  2.09it/s]

370000 totalt klara...

Chunk 11:  50%|██████████████▌              | 2500/5000 [42:28<33:11,  1.26it/s]

Checkpoint sparad (370000)

Chunk 11:  60%|█████████████████▍           | 2999/5000 [50:41<14:44,  2.26it/s]

370500 totalt klara...

Chunk 11:  60%|█████████████████▍           | 3000/5000 [50:42<19:09,  1.74it/s]

Checkpoint sparad (370500)

Chunk 11:  70%|████████████████████▎        | 3499/5000 [58:57<19:24,  1.29it/s]

371000 totalt klara...

Chunk 11:  70%|████████████████████▎        | 3500/5000 [58:58<20:06,  1.24it/s]

Checkpoint sparad (371000)

Chunk 14:  20%|█████▉                        | 999/5000 [17:07<37:38,  1.77it/s]

383500 totalt klara...

Chunk 14:  20%|█████▊                       | 1000/5000 [17:08<43:19,  1.54it/s]

Checkpoint sparad (383500)

Chunk 14:  30%|████████▋                    | 1498/5000 [25:25<29:21,  1.99it/s]

384000 totalt klara...

Chunk 14:  30%|████████▋                    | 1500/5000 [25:25<22:31,  2.59it/s]

Checkpoint sparad (384000)

Chunk 15: 100%|██████████████████████████▉| 4999/5000 [1:41:01<00:00,  1.97it/s]

392500 totalt klara...

Chunk 15: 100%|███████████████████████████| 5000/5000 [1:41:02<00:00,  1.21s/it]

Checkpoint sparad (392500)

Startar chunk 16 (5000 URL:er)

Chunk 16:  10%|██▊                         | 499/5000 [20:48<3:15:26,  2.61s/it]

393000 totalt klara...
Checkpoint sparad (393000)

Chunk 16:  10%|██▋                        | 500/5000 [21:21<14:31:47, 11.62s/it]

Chunk 16:  15%|████▏                       | 740/5000 [34:07<3:36:51,  3.05s/it]IOStream.flush timed out
Chunk 16:  46%|███████████▌             | 2322/5000 [2:01:58<3:22:27,  4.54s/it]IOStream.flush timed out
Chunk 16:  50%|████████████▍            | 2499/5000 [2:11:42<2:47:06,  4.01s/it]

395000 totalt klara...

Chunk 16:  50%|████████████▌            | 2501/5000 [2:12:13<6:04:31,  8.75s/it]

Checkpoint sparad (395000)

Chunk 16:  56%|██████████████           | 2803/5000 [2:28:33<3:28:54,  5.71s/it]IOStream.flush timed out
Chunk 16:  60%|██████████████▉          | 2999/5000 [2:39:16<1:11:27,  2.14s/it]

395500 totalt klara...

Chunk 16:  60%|███████████████          | 3000/5000 [2:39:32<3:26:44,  6.20s/it]

Checkpoint sparad (395500)

Chunk 16:  62%|████████████████▊          | 3104/5000 [2:41:10<05:24,  5.84it/s]

396000 totalt klara...

Chunk 16:  70%|██████████████████▏       | 3500/5000 [2:41:12<00:05, 257.69it/s]

Checkpoint sparad (396000)
396500 totalt klara...

Chunk 16:  80%|████████████████████▊     | 4000/5000 [2:41:12<00:02, 481.30it/s]

Checkpoint sparad (396500)
397000 totalt klara...

Chunk 16:  90%|███████████████████████▍  | 4500/5000 [2:41:13<00:00, 622.38it/s]

Checkpoint sparad (397000)
397500 totalt klara...

Chunk 16: 100%|███████████████████████████| 5000/5000 [2:41:13<00:00,  1.93s/it]

Checkpoint sparad (397500)

Startar chunk 17 (5000 URL:er)

Chunk 17:   9%|██▍                         | 444/5000 [17:09<4:33:22,  3.60s/it]IOStream.flush timed out
Chunk 17:  10%|██▊                         | 499/5000 [20:29<5:57:33,  4.77s/it]

398000 totalt klara...

Chunk 17:  10%|██▋                        | 500/5000 [20:49<11:55:55,  9.55s/it]

Checkpoint sparad (398000)

Chunk 17:  20%|█████▌                      | 999/5000 [48:32<3:45:56,  3.39s/it]

398500 totalt klara...

Chunk 17:  20%|█████▍                     | 1000/5000 [48:47<7:36:50,  6.85s/it]

Checkpoint sparad (398500)

Chunk 17:  24%|██████▍                    | 1190/5000 [59:34<3:26:47,  3.26s/it]IOStream.flush timed out
Chunk 17:  30%|███████▍                 | 1499/5000 [1:13:34<3:11:55,  3.29s/it]

399000 totalt klara...

Chunk 17:  30%|███████▌                 | 1500/5000 [1:13:55<8:28:57,  8.73s/it]

Checkpoint sparad (399000)

Chunk 17:  36%|█████████                | 1800/5000 [1:29:44<6:45:52,  7.61s/it]IOStream.flush timed out
Chunk 17:  40%|██████████▊                | 1993/5000 [1:34:54<56:41,  1.13s/it]

399500 totalt klara...

Chunk 17:  40%|██████████▊                | 2001/5000 [1:34:58<33:08,  1.51it/s]

Checkpoint sparad (399500)

Chunk 17:  42%|███████████▎               | 2101/5000 [1:36:14<28:50,  1.67it/s]

400000 totalt klara...

Chunk 17:  50%|█████████████             | 2509/5000 [1:36:15<00:18, 136.68it/s]

Checkpoint sparad (400000)

Chunk 17:  51%|█████████████▊             | 2557/5000 [1:36:17<00:58, 41.43it/s]

400500 totalt klara...

Chunk 17:  60%|███████████████▌          | 3000/5000 [1:36:18<00:08, 248.90it/s]

Checkpoint sparad (400500)

Chunk 17:  70%|██████████████████▉        | 3499/5000 [1:38:43<14:53,  1.68it/s]

401000 totalt klara...

Chunk 17:  70%|██████████████████▉        | 3500/5000 [1:38:44<13:25,  1.86it/s]

Checkpoint sparad (401000)

Chunk 17:  73%|███████████████████▊       | 3670/5000 [1:41:44<24:15,  1.09s/it]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Chunk 19:  30%|████████▋                    | 1499/5000 [25:28<29:27,  1.98it/s]

409000 totalt klara...

Chunk 19:  30%|████████▋                    | 1501/5000 [25:29<24:39,  2.36it/s]

Checkpoint sparad (409000)

Chunk 19:  40%|███████████▌                 | 1999/5000 [33:41<21:41,  2.31it/s]

409500 totalt klara...

Chunk 19:  40%|███████████▌                 | 2000/5000 [33:42<29:00,  1.72it/s]

Checkpoint sparad (409500)

Chunk 19:  50%|██████████████▍              | 2499/5000 [42:35<27:15,  1.53it/s]

410000 totalt klara...

Chunk 19:  50%|██████████████▌              | 2500/5000 [42:37<35:20,  1.18it/s]

Checkpoint sparad (410000)

Chunk 20:  30%|████████▋                    | 1499/5000 [25:19<31:01,  1.88it/s]

414000 totalt klara...

Chunk 20:  30%|████████▋                    | 1500/5000 [25:20<36:42,  1.59it/s]

Checkpoint sparad (414000)

Chunk 20:  60%|█████████████████▍           | 2999/5000 [50:39<16:12,  2.06it/s]

415500 totalt klara...

Chunk 20:  60%|█████████████████▍           | 3001/5000 [50:40<15:23,  2.16it/s]

Checkpoint sparad (415500)

Chunk 20:  80%|█████████████████████▌     | 3999/5000 [1:07:16<24:57,  1.50s/it]

416500 totalt klara...

Chunk 20:  80%|█████████████████████▌     | 4000/5000 [1:07:18<26:26,  1.59s/it]

Checkpoint sparad (416500)

Chunk 20:  90%|████████████████████████▎  | 4499/5000 [1:16:03<04:56,  1.69it/s]

417000 totalt klara...

Chunk 20:  90%|████████████████████████▎  | 4501/5000 [1:16:04<04:14,  1.96it/s]

Checkpoint sparad (417000)

Chunk 20: 100%|██████████████████████████▉| 4999/5000 [1:23:57<00:00,  2.00it/s]

417500 totalt klara...

Chunk 20: 100%|███████████████████████████| 5000/5000 [1:23:58<00:00,  1.01s/it]

Checkpoint sparad (417500)

Startar chunk 21 (5000 URL:er)

Chunk 21:  20%|█████▉                        | 999/5000 [17:05<33:16,  2.00it/s]

418500 totalt klara...

Chunk 21:  20%|█████▊                       | 1000/5000 [17:06<44:36,  1.49it/s]

Checkpoint sparad (418500)

Chunk 21:  30%|████████▋                    | 1499/5000 [25:18<29:04,  2.01it/s]

419000 totalt klara...

Chunk 21:  30%|████████▋                    | 1500/5000 [25:19<36:05,  1.62it/s]

Checkpoint sparad (419000)

Chunk 21:  40%|███████████▌                 | 1999/5000 [33:32<25:00,  2.00it/s]

419500 totalt klara...

Chunk 21:  40%|███████████▌                 | 2000/5000 [33:33<30:20,  1.65it/s]

Checkpoint sparad (419500)

Chunk 21:  50%|██████████████▍              | 2499/5000 [42:26<21:35,  1.93it/s]

420000 totalt klara...

Chunk 21:  50%|██████████████▌              | 2500/5000 [42:27<26:39,  1.56it/s]

Checkpoint sparad (420000)

Chunk 21:  60%|█████████████████▍           | 2999/5000 [50:39<16:38,  2.00it/s]

420500 totalt klara...

Chunk 21:  60%|█████████████████▍           | 3000/5000 [50:40<21:41,  1.54it/s]

Checkpoint sparad (420500)

Chunk 21:  70%|████████████████████▎        | 3499/5000 [58:53<12:35,  1.99it/s]

421000 totalt klara...

Chunk 21:  70%|████████████████████▎        | 3500/5000 [58:54<17:37,  1.42it/s]

Checkpoint sparad (421000)

Chunk 21:  80%|█████████████████████▌     | 3999/5000 [1:07:07<08:16,  2.02it/s]

421500 totalt klara...

Chunk 21:  80%|█████████████████████▌     | 4000/5000 [1:07:08<10:32,  1.58it/s]

Checkpoint sparad (421500)

Chunk 22:  20%|█████▉                        | 999/5000 [17:34<36:18,  1.84it/s]

423500 totalt klara...

Chunk 22:  20%|█████▊                       | 1001/5000 [17:35<32:46,  2.03it/s]

Checkpoint sparad (423500)

Chunk 22:  30%|████████▋                    | 1499/5000 [25:48<29:34,  1.97it/s]

424000 totalt klara...

Chunk 22:  30%|████████▋                    | 1500/5000 [25:49<38:34,  1.51it/s]

Checkpoint sparad (424000)

Chunk 23:  10%|██▉                           | 499/5000 [08:52<43:23,  1.73it/s]

428000 totalt klara...

Chunk 23:  10%|███                           | 500/5000 [08:53<45:19,  1.65it/s]

Checkpoint sparad (428000)

Chunk 23:  20%|█████▉                        | 999/5000 [17:06<32:05,  2.08it/s]

428500 totalt klara...

Chunk 23:  20%|█████▊                       | 1000/5000 [17:07<47:33,  1.40it/s]

Checkpoint sparad (428500)

Chunk 23:  30%|████████▋                    | 1499/5000 [25:19<25:54,  2.25it/s]

429000 totalt klara...

Chunk 23:  30%|████████▋                    | 1500/5000 [25:20<34:39,  1.68it/s]

Checkpoint sparad (429000)

Chunk 24:  20%|█████▉                        | 999/5000 [17:05<32:56,  2.02it/s]

433500 totalt klara...

Chunk 24:  20%|█████▊                       | 1000/5000 [17:06<38:39,  1.72it/s]

Checkpoint sparad (433500)

Chunk 24:  30%|████████▋                    | 1499/5000 [25:19<32:10,  1.81it/s]

434000 totalt klara...

Chunk 24:  30%|████████▋                    | 1501/5000 [25:20<26:14,  2.22it/s]

Checkpoint sparad (434000)

Chunk 24:  40%|███████████▌                 | 1999/5000 [33:32<24:08,  2.07it/s]

434500 totalt klara...

Chunk 24:  40%|███████████▌                 | 2000/5000 [33:33<35:45,  1.40it/s]

Checkpoint sparad (434500)

Chunk 24:  50%|██████████████▍              | 2499/5000 [42:26<20:32,  2.03it/s]

435000 totalt klara...

Chunk 24:  50%|██████████████▌              | 2500/5000 [42:27<25:17,  1.65it/s]

Checkpoint sparad (435000)

Chunk 24:  60%|█████████████████▍           | 2999/5000 [50:40<19:02,  1.75it/s]

435500 totalt klara...

Chunk 24:  60%|█████████████████▍           | 3000/5000 [50:41<21:10,  1.57it/s]

Checkpoint sparad (435500)

Chunk 24:  70%|████████████████████▎        | 3499/5000 [58:53<11:58,  2.09it/s]

436000 totalt klara...

Chunk 24:  70%|████████████████████▎        | 3500/5000 [58:54<16:13,  1.54it/s]

Checkpoint sparad (436000)

Chunk 24:  80%|█████████████████████▌     | 3999/5000 [1:07:07<07:32,  2.21it/s]

436500 totalt klara...

Chunk 24:  80%|█████████████████████▌     | 4000/5000 [1:07:08<10:28,  1.59it/s]

Checkpoint sparad (436500)

Chunk 24:  90%|████████████████████████▎  | 4499/5000 [1:16:02<04:47,  1.74it/s]

437000 totalt klara...

Chunk 24:  90%|████████████████████████▎  | 4501/5000 [1:16:02<03:46,  2.21it/s]

Checkpoint sparad (437000)

Chunk 24: 100%|██████████████████████████▉| 4999/5000 [1:23:55<00:00,  2.06it/s]

437500 totalt klara...

Chunk 24: 100%|███████████████████████████| 5000/5000 [1:23:56<00:00,  1.01s/it]

Checkpoint sparad (437500)

Startar chunk 25 (5000 URL:er)

Chunk 25:  10%|██▉                           | 499/5000 [08:52<37:07,  2.02it/s]

438000 totalt klara...

Chunk 25:  10%|███                           | 500/5000 [08:53<47:07,  1.59it/s]

Checkpoint sparad (438000)

Chunk 25:  20%|█████▉                        | 999/5000 [17:06<38:43,  1.72it/s]

438500 totalt klara...

Chunk 25:  20%|█████▊                       | 1000/5000 [17:06<42:54,  1.55it/s]

Checkpoint sparad (438500)

Chunk 25:  30%|████████▋                    | 1499/5000 [25:19<28:09,  2.07it/s]

439000 totalt klara...

Chunk 25:  30%|████████▋                    | 1500/5000 [25:20<39:10,  1.49it/s]

Checkpoint sparad (439000)

Chunk 25:  40%|███████████▌                 | 1999/5000 [33:33<23:57,  2.09it/s]

439500 totalt klara...

Chunk 25:  40%|███████████▌                 | 2000/5000 [33:34<30:47,  1.62it/s]

Checkpoint sparad (439500)

Chunk 25:  50%|██████████████▍              | 2499/5000 [42:30<23:38,  1.76it/s]

440000 totalt klara...

Chunk 25:  50%|██████████████▌              | 2500/5000 [42:30<25:08,  1.66it/s]

Checkpoint sparad (440000)

Chunk 25:  60%|█████████████████▍           | 2999/5000 [50:46<16:08,  2.07it/s]

440500 totalt klara...

Chunk 25:  60%|█████████████████▍           | 3000/5000 [50:47<21:50,  1.53it/s]

Checkpoint sparad (440500)

Chunk 25:  70%|████████████████████▎        | 3499/5000 [59:02<12:03,  2.07it/s]

441000 totalt klara...

Chunk 25:  70%|████████████████████▎        | 3500/5000 [59:03<14:49,  1.69it/s]

Checkpoint sparad (441000)

Chunk 25:  80%|█████████████████████▌     | 3999/5000 [1:07:20<09:25,  1.77it/s]

441500 totalt klara...

Chunk 25:  80%|█████████████████████▌     | 4000/5000 [1:07:21<09:49,  1.70it/s]

Checkpoint sparad (441500)

Chunk 25:  90%|████████████████████████▎  | 4499/5000 [1:16:18<04:21,  1.92it/s]

442000 totalt klara...

Chunk 25:  90%|████████████████████████▎  | 4500/5000 [1:16:19<05:37,  1.48it/s]

Checkpoint sparad (442000)

Chunk 25: 100%|██████████████████████████▉| 4999/5000 [1:24:16<00:00,  2.08it/s]

442500 totalt klara...

Chunk 25: 100%|███████████████████████████| 5000/5000 [1:24:16<00:00,  1.01s/it]

Checkpoint sparad (442500)

Startar chunk 26 (5000 URL:er)

Chunk 26:  10%|██▉                           | 499/5000 [08:57<43:38,  1.72it/s]

443000 totalt klara...

Chunk 26:  10%|███                           | 500/5000 [08:58<45:50,  1.64it/s]

Checkpoint sparad (443000)

Chunk 26:  20%|█████▉                        | 999/5000 [17:15<32:27,  2.05it/s]

443500 totalt klara...

Chunk 26:  20%|█████▊                       | 1000/5000 [17:16<42:52,  1.56it/s]

Checkpoint sparad (443500)

Chunk 26:  30%|████████▋                    | 1499/5000 [25:32<28:13,  2.07it/s]

444000 totalt klara...

Chunk 26:  30%|████████▋                    | 1500/5000 [25:33<34:58,  1.67it/s]

Checkpoint sparad (444000)

Chunk 26:  40%|███████████▌                 | 1999/5000 [33:50<27:43,  1.80it/s]

444500 totalt klara...

Chunk 26:  40%|███████████▌                 | 2000/5000 [33:51<29:37,  1.69it/s]

Checkpoint sparad (444500)

Chunk 26:  50%|██████████████▍              | 2499/5000 [42:48<21:00,  1.98it/s]

445000 totalt klara...

Chunk 26:  50%|██████████████▌              | 2500/5000 [42:49<28:11,  1.48it/s]

Checkpoint sparad (445000)

Chunk 26:  60%|█████████████████▍           | 2999/5000 [51:05<16:01,  2.08it/s]

445500 totalt klara...

Chunk 26:  60%|█████████████████▍           | 3000/5000 [51:06<19:35,  1.70it/s]

Checkpoint sparad (445500)

Chunk 26:  70%|████████████████████▎        | 3499/5000 [59:23<13:26,  1.86it/s]

446000 totalt klara...

Chunk 26:  70%|████████████████████▎        | 3501/5000 [59:24<11:13,  2.23it/s]

Checkpoint sparad (446000)

Chunk 26:  80%|█████████████████████▌     | 3999/5000 [1:07:41<07:46,  2.15it/s]

446500 totalt klara...

Chunk 26:  80%|█████████████████████▌     | 4000/5000 [1:07:42<10:08,  1.64it/s]

Checkpoint sparad (446500)

Chunk 26:  90%|████████████████████████▎  | 4499/5000 [1:16:40<04:14,  1.97it/s]

447000 totalt klara...

Chunk 26:  90%|████████████████████████▎  | 4500/5000 [1:16:41<05:24,  1.54it/s]

Checkpoint sparad (447000)

Chunk 26: 100%|██████████████████████████▉| 4999/5000 [1:24:37<00:00,  2.07it/s]

447500 totalt klara...

Chunk 26: 100%|███████████████████████████| 5000/5000 [1:24:38<00:00,  1.02s/it]

Checkpoint sparad (447500)

Startar chunk 27 (5000 URL:er)

Chunk 27:  10%|██▉                           | 499/5000 [08:57<44:24,  1.69it/s]

448000 totalt klara...

Chunk 27:  10%|███                           | 500/5000 [08:58<44:59,  1.67it/s]

Checkpoint sparad (448000)

Chunk 27:  20%|█████▉                        | 999/5000 [17:11<32:45,  2.04it/s]

448500 totalt klara...

Chunk 27:  20%|█████▊                       | 1000/5000 [17:12<44:43,  1.49it/s]

Checkpoint sparad (448500)

Chunk 27:  30%|████████▋                    | 1499/5000 [25:24<26:24,  2.21it/s]

449000 totalt klara...

Chunk 27:  30%|████████▋                    | 1500/5000 [25:25<35:13,  1.66it/s]

Checkpoint sparad (449000)

Chunk 27:  40%|███████████▌                 | 1999/5000 [33:38<26:23,  1.90it/s]

449500 totalt klara...

Chunk 27:  40%|███████████▌                 | 2000/5000 [33:39<29:46,  1.68it/s]

Checkpoint sparad (449500)

Chunk 27:  50%|██████████████▍              | 2499/5000 [42:32<23:45,  1.75it/s]

450000 totalt klara...

Chunk 27:  50%|██████████████▌              | 2500/5000 [42:32<25:58,  1.60it/s]

Checkpoint sparad (450000)

Chunk 27:  60%|█████████████████▍           | 2999/5000 [50:45<16:08,  2.07it/s]

450500 totalt klara...

Chunk 27:  60%|█████████████████▍           | 3000/5000 [50:46<22:12,  1.50it/s]

Checkpoint sparad (450500)

Chunk 27:  70%|████████████████████▎        | 3499/5000 [58:59<12:57,  1.93it/s]

451000 totalt klara...

Chunk 27:  70%|████████████████████▎        | 3500/5000 [59:00<15:10,  1.65it/s]

Checkpoint sparad (451000)

Chunk 28:  20%|█████▉                        | 999/5000 [17:06<33:13,  2.01it/s]

453500 totalt klara...

Chunk 28:  20%|█████▊                       | 1000/5000 [17:07<45:30,  1.47it/s]

Checkpoint sparad (453500)

Chunk 28:  50%|██████████████▍              | 2499/5000 [42:27<21:42,  1.92it/s]

455000 totalt klara...

Chunk 28:  50%|██████████████▌              | 2500/5000 [42:28<28:58,  1.44it/s]

Checkpoint sparad (455000)

Chunk 30:  40%|███████████▌                 | 1999/5000 [33:37<30:37,  1.63it/s]

464500 totalt klara...

Chunk 30:  40%|██████████▊                | 2000/5000 [33:40<1:07:18,  1.35s/it]

Checkpoint sparad (464500)

Chunk 30:  50%|██████████████▍              | 2499/5000 [42:30<21:48,  1.91it/s]

465000 totalt klara...

Chunk 30:  50%|██████████████▌              | 2500/5000 [42:31<26:44,  1.56it/s]

Checkpoint sparad (465000)

Chunk 30:  60%|█████████████████▍           | 2999/5000 [50:44<16:51,  1.98it/s]

465500 totalt klara...

Chunk 30:  60%|█████████████████▍           | 3000/5000 [50:45<22:38,  1.47it/s]

Checkpoint sparad (465500)

Chunk 30:  70%|████████████████████▎        | 3499/5000 [58:58<12:38,  1.98it/s]

466000 totalt klara...

Chunk 30:  70%|████████████████████▎        | 3500/5000 [58:59<15:46,  1.58it/s]

Checkpoint sparad (466000)

Chunk 30:  80%|█████████████████████▌     | 3999/5000 [1:07:12<10:10,  1.64it/s]

466500 totalt klara...

Chunk 30:  80%|█████████████████████▌     | 4000/5000 [1:07:15<21:39,  1.30s/it]

Checkpoint sparad (466500)

Chunk 30:  90%|████████████████████████▎  | 4499/5000 [1:16:05<04:20,  1.93it/s]

467000 totalt klara...

Chunk 30:  90%|████████████████████████▎  | 4501/5000 [1:16:06<04:03,  2.05it/s]

Checkpoint sparad (467000)

Chunk 30: 100%|██████████████████████████▉| 4999/5000 [1:23:59<00:00,  1.99it/s]

467500 totalt klara...

Chunk 30: 100%|███████████████████████████| 5000/5000 [1:24:00<00:00,  1.01s/it]

Checkpoint sparad (467500)

Startar chunk 31 (5000 URL:er)

Chunk 31:  10%|██▉                           | 499/5000 [08:52<38:38,  1.94it/s]

468000 totalt klara...

Chunk 31:  10%|███                           | 500/5000 [08:53<53:44,  1.40it/s]

Checkpoint sparad (468000)

Chunk 31:  40%|███████████▌                 | 1999/5000 [33:33<25:20,  1.97it/s]

469500 totalt klara...

Chunk 31:  40%|███████████▌                 | 2000/5000 [33:34<37:37,  1.33it/s]

Checkpoint sparad (469500)

Chunk 31:  80%|█████████████████████▌     | 3999/5000 [1:07:08<09:03,  1.84it/s]

471500 totalt klara...

Chunk 31:  80%|█████████████████████▌     | 4000/5000 [1:07:09<12:24,  1.34it/s]

Checkpoint sparad (471500)

Chunk 31:  90%|████████████████████████▎  | 4499/5000 [1:16:01<04:21,  1.91it/s]

472000 totalt klara...

Chunk 31:  90%|████████████████████████▎  | 4501/5000 [1:16:02<03:58,  2.09it/s]

Checkpoint sparad (472000)

Chunk 31: 100%|██████████████████████████▉| 4999/5000 [1:23:55<00:00,  1.94it/s]

472500 totalt klara...

Chunk 31: 100%|███████████████████████████| 5000/5000 [1:23:56<00:00,  1.01s/it]

Checkpoint sparad (472500)

Startar chunk 32 (5000 URL:er)

Chunk 32:  40%|███████████▌                 | 1999/5000 [33:33<25:12,  1.98it/s]

474500 totalt klara...

Chunk 32:  40%|███████████▌                 | 2000/5000 [33:34<35:41,  1.40it/s]

Checkpoint sparad (474500)

Chunk 32:  50%|██████████████▍              | 2499/5000 [42:30<22:11,  1.88it/s]

475000 totalt klara...

Chunk 32:  50%|██████████████▌              | 2500/5000 [42:31<27:14,  1.53it/s]

Checkpoint sparad (475000)

Chunk 32:  60%|█████████████████▍           | 2999/5000 [50:48<16:54,  1.97it/s]

475500 totalt klara...

Chunk 32:  60%|█████████████████▍           | 3001/5000 [50:49<15:40,  2.13it/s]

Checkpoint sparad (475500)

Chunk 32:  70%|████████████████████▎        | 3499/5000 [59:05<12:33,  1.99it/s]

476000 totalt klara...

Chunk 32:  70%|████████████████████▎        | 3501/5000 [59:06<11:42,  2.13it/s]

Checkpoint sparad (476000)

Chunk 32:  80%|█████████████████████▌     | 3999/5000 [1:07:23<08:26,  1.97it/s]

476500 totalt klara...

Chunk 32:  80%|█████████████████████▌     | 4000/5000 [1:07:24<10:29,  1.59it/s]

Checkpoint sparad (476500)

Chunk 32:  90%|████████████████████████▎  | 4499/5000 [1:16:21<04:23,  1.90it/s]

477000 totalt klara...

Chunk 32:  90%|████████████████████████▎  | 4501/5000 [1:16:22<03:59,  2.09it/s]

Checkpoint sparad (477000)

Chunk 32: 100%|██████████████████████████▉| 4999/5000 [1:24:18<00:00,  1.97it/s]

477500 totalt klara...

Chunk 32: 100%|███████████████████████████| 5000/5000 [1:24:19<00:00,  1.01s/it]

Checkpoint sparad (477500)

Startar chunk 33 (5000 URL:er)

Chunk 33:  10%|██▉                           | 499/5000 [08:57<39:38,  1.89it/s]

478000 totalt klara...

Chunk 33:  10%|███                           | 500/5000 [08:58<50:08,  1.50it/s]

Checkpoint sparad (478000)

Chunk 33:  20%|█████▉                        | 999/5000 [17:21<41:10,  1.62it/s]

478500 totalt klara...

Chunk 33:  20%|█████▊                       | 1001/5000 [17:22<35:01,  1.90it/s]

Checkpoint sparad (478500)

Chunk 33:  30%|████████                   | 1499/5000 [25:54<1:23:02,  1.42s/it]

479000 totalt klara...

Chunk 33:  30%|████████                   | 1500/5000 [25:56<1:30:52,  1.56s/it]

Checkpoint sparad (479000)

Chunk 33:  40%|███████████▌                 | 1999/5000 [34:30<26:51,  1.86it/s]

479500 totalt klara...

Chunk 33:  40%|███████████▌                 | 2000/5000 [34:31<32:08,  1.56it/s]

Checkpoint sparad (479500)

Chunk 33:  50%|██████████████▍              | 2499/5000 [42:54<38:50,  1.07it/s]

480000 totalt klara...

Chunk 33:  50%|██████████████▌              | 2501/5000 [42:55<28:18,  1.47it/s]

Checkpoint sparad (480000)

Chunk 33:  60%|█████████████████▍           | 2999/5000 [51:12<20:37,  1.62it/s]

480500 totalt klara...

Chunk 33:  60%|█████████████████▍           | 3000/5000 [51:13<24:00,  1.39it/s]

Checkpoint sparad (480500)

Chunk 33:  70%|████████████████████▎        | 3499/5000 [59:44<35:33,  1.42s/it]

481000 totalt klara...

Chunk 33:  70%|████████████████████▎        | 3500/5000 [59:46<39:54,  1.60s/it]

Checkpoint sparad (481000)

Chunk 33:  80%|█████████████████████▌     | 3999/5000 [1:08:20<08:55,  1.87it/s]

481500 totalt klara...

Chunk 33:  80%|█████████████████████▌     | 4000/5000 [1:08:21<10:49,  1.54it/s]

Checkpoint sparad (481500)

Chunk 33:  90%|████████████████████████▎  | 4499/5000 [1:16:44<07:45,  1.08it/s]

482000 totalt klara...

Chunk 33:  90%|████████████████████████▎  | 4501/5000 [1:16:45<05:39,  1.47it/s]

Checkpoint sparad (482000)

Chunk 33: 100%|██████████████████████████▉| 4999/5000 [1:24:50<00:00,  1.97it/s]

482500 totalt klara...

Chunk 33: 100%|███████████████████████████| 5000/5000 [1:24:51<00:00,  1.02s/it]

Checkpoint sparad (482500)

Startar chunk 34 (5000 URL:er)

Chunk 34:  10%|██▉                           | 499/5000 [08:57<39:36,  1.89it/s]

483000 totalt klara...

Chunk 34:  10%|███                           | 500/5000 [08:58<48:31,  1.55it/s]

Checkpoint sparad (483000)

Chunk 34:  20%|█████▉                        | 999/5000 [17:14<33:56,  1.96it/s]

483500 totalt klara...

Chunk 34:  20%|█████▊                       | 1000/5000 [17:15<42:03,  1.59it/s]

Checkpoint sparad (483500)

Chunk 34:  30%|████████▋                    | 1499/5000 [25:32<29:53,  1.95it/s]

484000 totalt klara...

Chunk 34:  30%|████████▋                    | 1501/5000 [25:33<27:27,  2.12it/s]

Checkpoint sparad (484000)

Chunk 34:  40%|███████████▌                 | 1999/5000 [33:50<25:22,  1.97it/s]

484500 totalt klara...

Chunk 34:  40%|███████████▌                 | 2000/5000 [33:50<31:05,  1.61it/s]

Checkpoint sparad (484500)

Chunk 34:  50%|██████████████▍              | 2499/5000 [42:48<22:12,  1.88it/s]

485000 totalt klara...

Chunk 34:  50%|██████████████▌              | 2501/5000 [42:49<20:03,  2.08it/s]

Checkpoint sparad (485000)

Chunk 34:  60%|█████████████████▍           | 2999/5000 [51:05<16:58,  1.96it/s]

485500 totalt klara...

Chunk 34:  60%|█████████████████▍           | 3001/5000 [51:06<15:40,  2.13it/s]

Checkpoint sparad (485500)

Chunk 34:  70%|████████████████████▎        | 3499/5000 [59:23<12:43,  1.97it/s]

486000 totalt klara...

Chunk 34:  70%|████████████████████▎        | 3501/5000 [59:24<12:42,  1.97it/s]

Checkpoint sparad (486000)

Chunk 34:  80%|█████████████████████▌     | 3999/5000 [1:07:40<08:30,  1.96it/s]

486500 totalt klara...

Chunk 34:  80%|█████████████████████▌     | 4000/5000 [1:07:41<10:54,  1.53it/s]

Checkpoint sparad (486500)

Chunk 34:  90%|████████████████████████▎  | 4499/5000 [1:16:39<04:24,  1.89it/s]

487000 totalt klara...

Chunk 34:  90%|████████████████████████▎  | 4500/5000 [1:16:39<05:23,  1.55it/s]

Checkpoint sparad (487000)

Chunk 34: 100%|██████████████████████████▉| 4999/5000 [1:24:36<00:00,  1.97it/s]

487500 totalt klara...

Chunk 34: 100%|███████████████████████████| 5000/5000 [1:24:37<00:00,  1.02s/it]

Checkpoint sparad (487500)

Startar chunk 35 (5000 URL:er)

Chunk 35:  10%|██▉                           | 499/5000 [08:57<39:46,  1.89it/s]

488000 totalt klara...

Chunk 35:  10%|███                           | 501/5000 [08:58<36:02,  2.08it/s]

Checkpoint sparad (488000)

Chunk 35:  20%|█████▉                        | 999/5000 [17:14<33:46,  1.97it/s]

488500 totalt klara...

Chunk 35:  20%|█████▊                       | 1000/5000 [17:15<42:19,  1.57it/s]

Checkpoint sparad (488500)

Chunk 35:  30%|████████▋                    | 1499/5000 [25:32<29:27,  1.98it/s]

489000 totalt klara...

Chunk 35:  30%|████████▋                    | 1500/5000 [25:33<36:56,  1.58it/s]

Checkpoint sparad (489000)

Chunk 35:  40%|███████████▌                 | 1999/5000 [33:49<25:24,  1.97it/s]

489500 totalt klara...

Chunk 35:  40%|███████████▌                 | 2000/5000 [33:50<31:28,  1.59it/s]

Checkpoint sparad (489500)

Chunk 35:  50%|██████████████▍              | 2499/5000 [42:48<22:11,  1.88it/s]

490000 totalt klara...

Chunk 35:  50%|██████████████▌              | 2500/5000 [42:49<28:01,  1.49it/s]

Checkpoint sparad (490000)

Chunk 35:  60%|█████████████████▍           | 2999/5000 [51:06<16:57,  1.97it/s]

490500 totalt klara...

Chunk 35:  60%|█████████████████▍           | 3000/5000 [51:07<21:09,  1.58it/s]

Checkpoint sparad (490500)

Chunk 35:  70%|████████████████████▎        | 3499/5000 [59:23<12:39,  1.98it/s]

491000 totalt klara...

Chunk 35:  70%|████████████████████▎        | 3500/5000 [59:24<16:03,  1.56it/s]

Checkpoint sparad (491000)

Chunk 35:  80%|█████████████████████▌     | 3999/5000 [1:07:41<08:34,  1.95it/s]

491500 totalt klara...

Chunk 35:  80%|█████████████████████▌     | 4000/5000 [1:07:42<10:26,  1.60it/s]

Checkpoint sparad (491500)

Chunk 35:  90%|████████████████████████▎  | 4499/5000 [1:16:39<04:23,  1.90it/s]

492000 totalt klara...

Chunk 35:  90%|████████████████████████▎  | 4500/5000 [1:16:40<05:22,  1.55it/s]

Checkpoint sparad (492000)

Chunk 35: 100%|██████████████████████████▉| 4999/5000 [1:24:36<00:00,  1.98it/s]

492500 totalt klara...

Chunk 35: 100%|███████████████████████████| 5000/5000 [1:24:37<00:00,  1.02s/it]

Checkpoint sparad (492500)

Startar chunk 36 (5000 URL:er)

Chunk 36:  10%|██▉                           | 499/5000 [08:57<39:58,  1.88it/s]

493000 totalt klara...

Chunk 36:  10%|███                           | 501/5000 [08:58<35:58,  2.08it/s]

Checkpoint sparad (493000)

Chunk 36:  20%|█████▉                        | 999/5000 [17:14<33:39,  1.98it/s]

493500 totalt klara...

Chunk 36:  20%|█████▊                       | 1000/5000 [17:15<41:37,  1.60it/s]

Checkpoint sparad (493500)

Chunk 36:  30%|████████▋                    | 1499/5000 [25:27<29:32,  1.97it/s]

494000 totalt klara...

Chunk 36:  30%|████████▋                    | 1500/5000 [25:28<37:07,  1.57it/s]

Checkpoint sparad (494000)

Chunk 36:  90%|████████████████████████▎  | 4499/5000 [1:16:08<04:19,  1.93it/s]

497000 totalt klara...

Chunk 36:  90%|████████████████████████▎  | 4500/5000 [1:16:10<05:56,  1.40it/s]

Checkpoint sparad (497000)

Chunk 36: 100%|██████████████████████████▉| 4999/5000 [1:24:03<00:00,  2.24it/s]

497500 totalt klara...

Chunk 36: 100%|███████████████████████████| 5000/5000 [1:24:04<00:00,  1.01s/it]

Checkpoint sparad (497500)

Startar chunk 37 (5000 URL:er)

Chunk 37:  10%|██▉                           | 499/5000 [08:53<45:42,  1.64it/s]

498000 totalt klara...

Chunk 37:  10%|███                           | 500/5000 [08:54<49:38,  1.51it/s]

Checkpoint sparad (498000)

Chunk 37:  20%|█████▉                        | 999/5000 [17:23<57:19,  1.16it/s]

498500 totalt klara...

Chunk 37:  20%|█████▍                     | 1000/5000 [17:24<1:10:22,  1.06s/it]

Checkpoint sparad (498500)

Chunk 37:  40%|██████████▊                | 1999/5000 [34:02<1:19:25,  1.59s/it]

499500 totalt klara...

Chunk 37:  40%|██████████▊                | 2000/5000 [34:04<1:34:09,  1.88s/it]

Checkpoint sparad (499500)

Chunk 37:  50%|██████████████▍              | 2499/5000 [42:47<28:58,  1.44it/s]

500000 totalt klara...

Chunk 37:  50%|██████████████▌              | 2500/5000 [42:48<36:23,  1.14it/s]

Checkpoint sparad (500000)

Chunk 37:  80%|█████████████████████▌     | 3999/5000 [1:07:42<32:24,  1.94s/it]

501500 totalt klara...

Chunk 37:  80%|████████████████████     | 4000/5000 [1:07:51<1:07:18,  4.04s/it]

Checkpoint sparad (501500)

Chunk 41:  10%|██▉                           | 499/5000 [08:52<48:44,  1.54it/s]

518000 totalt klara...

Chunk 41:  10%|██▊                         | 500/5000 [08:54<1:01:48,  1.21it/s]

Checkpoint sparad (518000)

Chunk 41:  30%|████████▋                    | 1499/5000 [25:22<28:52,  2.02it/s]

519000 totalt klara...

Chunk 41:  30%|████████▋                    | 1500/5000 [25:24<42:35,  1.37it/s]

Checkpoint sparad (519000)

Chunk 42:  90%|████████████████████████▎  | 4499/5000 [1:16:22<04:09,  2.01it/s]

527000 totalt klara...

Chunk 42:  90%|████████████████████████▎  | 4500/5000 [1:16:24<07:51,  1.06it/s]

Checkpoint sparad (527000)

Chunk 42: 100%|██████████████████████████▉| 4999/5000 [1:24:22<00:01,  1.09s/it]

527500 totalt klara...

Chunk 42: 100%|███████████████████████████| 5000/5000 [1:24:24<00:00,  1.01s/it]

Checkpoint sparad (527500)

Startar chunk 43 (5000 URL:er)

Chunk 45:  50%|██████████████▍              | 2499/5000 [42:31<24:43,  1.69it/s]

540000 totalt klara...

Chunk 45:  50%|██████████████▌              | 2500/5000 [42:33<32:01,  1.30it/s]

Checkpoint sparad (540000)

Chunk 48:  70%|████████████████████▎        | 3499/5000 [58:57<12:35,  1.99it/s]

556000 totalt klara...

Chunk 48:  70%|████████████████████▎        | 3500/5000 [58:59<24:41,  1.01it/s]

Checkpoint sparad (556000)

Chunk 48:  80%|█████████████████████▌     | 3999/5000 [1:07:46<44:15,  2.65s/it]

556500 totalt klara...

Chunk 48:  80%|█████████████████████▌     | 4000/5000 [1:07:50<46:26,  2.79s/it]

Checkpoint sparad (556500)

Chunk 49:  70%|████████████████████▎        | 3499/5000 [59:03<26:43,  1.07s/it]

561000 totalt klara...

Chunk 49:  70%|████████████████████▎        | 3501/5000 [59:06<29:24,  1.18s/it]

Checkpoint sparad (561000)

Chunk 49:  80%|█████████████████████▌     | 3999/5000 [1:18:43<45:02,  2.70s/it]

561500 totalt klara...

Chunk 49:  80%|████████████████████     | 4000/5000 [1:19:26<4:09:11, 14.95s/it]

Checkpoint sparad (561500)

Chunk 52:  60%|████████████████▏          | 2999/5000 [1:03:45<19:50,  1.68it/s]

575500 totalt klara...

Chunk 52:  60%|████████████████▏          | 3000/5000 [1:03:47<32:07,  1.04it/s]

Checkpoint sparad (575500)

Chunk 53:  10%|██▊                         | 499/5000 [25:38<4:05:02,  3.27s/it]

578000 totalt klara...
Checkpoint sparad (578000)

Chunk 53:  60%|████████████████▏          | 2999/5000 [1:54:20<31:46,  1.05it/s]

580500 totalt klara...

Chunk 53:  60%|████████████████▏          | 3001/5000 [1:54:24<40:02,  1.20s/it]

Checkpoint sparad (580500)

Chunk 53:  70%|██████████████████▉        | 3499/5000 [2:02:52<41:10,  1.65s/it]

581000 totalt klara...

Chunk 53:  70%|██████████████████▉        | 3500/5000 [2:02:54<44:08,  1.77s/it]

Checkpoint sparad (581000)

Chunk 53:  80%|█████████████████████▌     | 3999/5000 [2:11:15<13:52,  1.20it/s]

581500 totalt klara...

Chunk 53:  80%|█████████████████████▌     | 4000/5000 [2:11:17<20:48,  1.25s/it]

Checkpoint sparad (581500)

Chunk 53:  90%|████████████████████████▎  | 4499/5000 [2:19:35<07:07,  1.17it/s]

582000 totalt klara...

Chunk 53:  90%|████████████████████████▎  | 4500/5000 [2:19:38<10:11,  1.22s/it]

Checkpoint sparad (582000)

Chunk 53: 100%|██████████████████████████▉| 4999/5000 [2:27:39<00:00,  1.99it/s]

582500 totalt klara...

Chunk 53: 100%|███████████████████████████| 5000/5000 [2:27:42<00:00,  1.77s/it]

Checkpoint sparad (582500)

Startar chunk 54 (5000 URL:er)

Chunk 54:  10%|██▉                           | 499/5000 [08:51<39:07,  1.92it/s]

583000 totalt klara...

Chunk 54:  10%|██▊                         | 500/5000 [08:54<1:35:00,  1.27s/it]

Checkpoint sparad (583000)

Chunk 54: 100%|██████████████████████████▉| 4999/5000 [1:25:09<00:00,  2.30it/s]

587500 totalt klara...

Chunk 54: 100%|███████████████████████████| 5000/5000 [1:25:12<00:00,  1.02s/it]

Checkpoint sparad (587500)

Startar chunk 55 (5000 URL:er)

Chunk 55:  10%|██▉                           | 499/5000 [08:52<41:31,  1.81it/s]

588000 totalt klara...

Chunk 55:  10%|██▊                         | 500/5000 [08:55<1:21:03,  1.08s/it]

Checkpoint sparad (588000)

Chunk 55:  20%|█████▉                        | 998/5000 [17:07<38:53,  1.72it/s]

588500 totalt klara...

Chunk 55:  20%|█████▍                     | 1000/5000 [17:09<1:00:39,  1.10it/s]

Checkpoint sparad (588500)

Chunk 55:  30%|████████▋                    | 1499/5000 [25:20<23:39,  2.47it/s]

589000 totalt klara...

Chunk 55:  30%|████████▋                    | 1500/5000 [25:22<47:49,  1.22it/s]

Checkpoint sparad (589000)

Chunk 55:  40%|██████████▊                | 1999/5000 [33:49<3:12:28,  3.85s/it]

589500 totalt klara...

Chunk 55:  40%|██████████▊                | 2000/5000 [34:00<5:01:35,  6.03s/it]

Checkpoint sparad (589500)

Chunk 55:  50%|██████████████▍              | 2499/5000 [42:27<21:50,  1.91it/s]

590000 totalt klara...

Chunk 55:  50%|██████████████▌              | 2500/5000 [42:29<47:18,  1.14s/it]

Checkpoint sparad (590000)

Chunk 56:  30%|████████▋                    | 1499/5000 [25:23<28:45,  2.03it/s]

594000 totalt klara...

Chunk 56:  30%|████████                   | 1500/5000 [25:26<1:07:48,  1.16s/it]

Checkpoint sparad (594000)

Chunk 57:  20%|█████▌                      | 999/5000 [18:46<1:05:52,  1.01it/s]

598500 totalt klara...

Chunk 57:  20%|█████▊                       | 1000/5000 [18:47<59:32,  1.12it/s]

Checkpoint sparad (598500)

Chunk 57:  30%|████████▋                    | 1499/5000 [27:53<37:05,  1.57it/s]

599000 totalt klara...

Chunk 57:  30%|████████                   | 1500/5000 [27:56<1:10:56,  1.22s/it]

Checkpoint sparad (599000)

Chunk 57:  40%|█████████▉               | 1999/5000 [1:11:48<1:04:57,  1.30s/it]

599500 totalt klara...

Chunk 57:  40%|██████████               | 2000/5000 [1:11:57<2:51:21,  3.43s/it]

Checkpoint sparad (599500)

Chunk 57:  50%|████████████▍            | 2498/5000 [1:57:11<1:18:39,  1.89s/it]

600000 totalt klara...

Chunk 57:  50%|█████████████▌             | 2500/5000 [1:57:12<56:19,  1.35s/it]

Checkpoint sparad (600000)

Chunk 57:  60%|████████████████▏          | 2999/5000 [3:54:59<28:23,  1.17it/s]

600500 totalt klara...

Chunk 57:  60%|████████████████▏          | 3000/5000 [3:55:01<35:12,  1.06s/it]

Checkpoint sparad (600500)

Chunk 57:  70%|██████████████████▉        | 3499/5000 [5:42:39<35:03,  1.40s/it]

601000 totalt klara...

Chunk 57:  70%|██████████████████▉        | 3500/5000 [5:42:40<30:42,  1.23s/it]

Checkpoint sparad (601000)

Chunk 57:  80%|█████████████████████▌     | 3999/5000 [6:51:05<11:52,  1.40it/s]

601500 totalt klara...

Chunk 57:  80%|█████████████████████▌     | 4000/5000 [6:51:06<15:48,  1.05it/s]

Checkpoint sparad (601500)

Chunk 57:  90%|████████████████████████▎  | 4499/5000 [6:58:05<07:18,  1.14it/s]

602000 totalt klara...

Chunk 57:  90%|████████████████████████▎  | 4500/5000 [6:58:07<11:01,  1.32s/it]

Checkpoint sparad (602000)

Chunk 57: 100%|██████████████████████████▉| 4999/5000 [7:04:55<00:00,  1.99it/s]

602500 totalt klara...

Chunk 57: 100%|███████████████████████████| 5000/5000 [7:04:56<00:00,  5.10s/it]

Checkpoint sparad (602500)

Startar chunk 58 (5000 URL:er)

Chunk 58:  10%|██▊                         | 499/5000 [07:08<1:00:38,  1.24it/s]

603000 totalt klara...

Chunk 58:  10%|██▊                         | 500/5000 [07:10<1:16:42,  1.02s/it]

Checkpoint sparad (603000)

Chunk 58:  20%|█████▌                      | 999/5000 [14:10<1:09:33,  1.04s/it]

603500 totalt klara...

Chunk 58:  20%|█████▍                     | 1000/5000 [14:12<1:20:35,  1.21s/it]

Checkpoint sparad (603500)

Chunk 58:  30%|████████▋                    | 1499/5000 [21:10<38:32,  1.51it/s]

604000 totalt klara...

Chunk 58:  30%|████████▋                    | 1500/5000 [21:12<54:53,  1.06it/s]

Checkpoint sparad (604000)

Chunk 58:  40%|██████████▊                | 1999/5000 [2:14:01<36:55,  1.35it/s]

604500 totalt klara...

Chunk 58:  40%|██████████▊                | 2000/5000 [2:14:03<55:19,  1.11s/it]

Checkpoint sparad (604500)

Chunk 58:  50%|█████████████▍             | 2499/5000 [2:21:04<33:00,  1.26it/s]

605000 totalt klara...

Chunk 58:  50%|█████████████▌             | 2500/5000 [2:21:07<58:29,  1.40s/it]

Checkpoint sparad (605000)

Chunk 58:  60%|████████████████▏          | 2999/5000 [2:28:08<25:25,  1.31it/s]

605500 totalt klara...

Chunk 58:  60%|████████████████▏          | 3000/5000 [2:28:08<25:23,  1.31it/s]

Checkpoint sparad (605500)

Chunk 58:  70%|██████████████████▉        | 3499/5000 [2:35:11<17:34,  1.42it/s]

606000 totalt klara...

Chunk 58:  70%|██████████████████▉        | 3500/5000 [2:35:12<23:29,  1.06it/s]

Checkpoint sparad (606000)

Chunk 58:  80%|█████████████████████▌     | 3999/5000 [2:42:16<20:34,  1.23s/it]

606500 totalt klara...

Chunk 58:  80%|█████████████████████▌     | 4000/5000 [2:42:17<20:43,  1.24s/it]

Checkpoint sparad (606500)

Chunk 58:  90%|████████████████████████▎  | 4499/5000 [2:49:32<10:10,  1.22s/it]

607000 totalt klara...

Chunk 58:  90%|████████████████████████▎  | 4500/5000 [2:49:33<09:36,  1.15s/it]

Checkpoint sparad (607000)

Chunk 58: 100%|██████████████████████████▉| 4999/5000 [2:57:45<00:00,  1.97it/s]

607500 totalt klara...

Chunk 58: 100%|███████████████████████████| 5000/5000 [2:57:46<00:00,  2.13s/it]

Checkpoint sparad (607500)

Startar chunk 59 (5000 URL:er)

Chunk 59:  10%|██▉                           | 498/5000 [08:57<47:28,  1.58it/s]

608000 totalt klara...

Chunk 59:  10%|███                           | 500/5000 [08:58<52:53,  1.42it/s]

Checkpoint sparad (608000)

Chunk 59:  20%|█████▉                        | 999/5000 [17:07<54:07,  1.23it/s]

608500 totalt klara...

Chunk 59:  20%|█████▊                       | 1000/5000 [17:08<58:44,  1.13it/s]

Checkpoint sparad (608500)

Chunk 59:  30%|████████▋                    | 1499/5000 [25:26<48:08,  1.21it/s]

609000 totalt klara...

Chunk 59:  30%|████████▋                    | 1500/5000 [25:27<54:23,  1.07it/s]

Checkpoint sparad (609000)

Chunk 59:  40%|███████████▌                 | 1999/5000 [33:50<45:55,  1.09it/s]

609500 totalt klara...

Chunk 59:  40%|███████████▌                 | 2000/5000 [33:51<47:26,  1.05it/s]

Checkpoint sparad (609500)

Chunk 59:  50%|█████████████▍             | 2499/5000 [42:37<1:02:05,  1.49s/it]

610000 totalt klara...

Chunk 59:  50%|██████████████▌              | 2500/5000 [42:38<59:37,  1.43s/it]

Checkpoint sparad (610000)

Chunk 59:  60%|██████████████▉          | 2999/5000 [1:54:46<6:50:30, 12.31s/it]

610500 totalt klara...

Chunk 59:  60%|███████████████          | 3000/5000 [1:54:48<5:05:40,  9.17s/it]

Checkpoint sparad (610500)

Chunk 59:  70%|██████████████████▉        | 3499/5000 [3:18:19<45:23,  1.81s/it]

611000 totalt klara...

Chunk 59:  70%|████████████████▊       | 3500/5000 [3:22:16<30:03:54, 72.16s/it]

Checkpoint sparad (611000)

Chunk 59:  80%|█████████████████████▌     | 3999/5000 [4:11:02<32:04,  1.92s/it]

611500 totalt klara...

Chunk 59:  80%|█████████████████████▌     | 4000/5000 [4:11:06<39:27,  2.37s/it]

Checkpoint sparad (611500)

Chunk 59:  90%|████████████████████████▎  | 4499/5000 [4:20:11<11:27,  1.37s/it]

612000 totalt klara...
Checkpoint sparad (612000)

Chunk 59: 100%|██████████████████████████▉| 4999/5000 [4:29:08<00:00,  1.26it/s]

612500 totalt klara...

Chunk 59: 100%|███████████████████████████| 5000/5000 [4:29:11<00:00,  3.23s/it]

Checkpoint sparad (612500)

Startar chunk 60 (2187 URL:er)

Chunk 60:  23%|██████▊                       | 499/2187 [10:12<19:50,  1.42it/s]

613000 totalt klara...

Chunk 60:  23%|██████▊                       | 500/2187 [10:15<45:02,  1.60s/it]

Checkpoint sparad (613000)

Chunk 60:  46%|█████████████▋                | 999/2187 [19:29<12:19,  1.61it/s]

613500 totalt klara...

Chunk 60:  46%|█████████████▎               | 1000/2187 [19:32<24:02,  1.22s/it]

Checkpoint sparad (613500)

Chunk 60:  69%|███████████████████▉         | 1499/2187 [27:49<12:23,  1.08s/it]

614000 totalt klara...

Chunk 60:  69%|███████████████████▉         | 1500/2187 [27:51<14:12,  1.24s/it]

Checkpoint sparad (614000)

Chunk 60:  91%|██████████████████████████▌  | 1999/2187 [36:25<07:25,  2.37s/it]

614500 totalt klara...

Chunk 60:  91%|██████████████████████████▌  | 2000/2187 [36:26<06:25,  2.06s/it]

Checkpoint sparad (614500)

Chunk 60: 100%|█████████████████████████████| 2187/2187 [39:14<00:00,  1.08s/it]

Startar chunk 2 (5000 URL:er)

Startar chunk 1 (5000 URL:er)

Chunk 1:   6%|█▊                           | 312/5000 [14:14<6:20:18,  4.87s/it]

615000 totalt klara...

Chunk 1:   6%|█▊                           | 314/5000 [14:18<4:11:03,  3.21s/it]

Checkpoint sparad (615000)

Chunk 1:  16%|████▋                        | 811/5000 [31:14<1:21:10,  1.16s/it]

615500 totalt klara...

Chunk 1:  16%|████▋                        | 813/5000 [31:17<1:32:57,  1.33s/it]

Checkpoint sparad (615500)

Chunk 1:  26%|███████▎                    | 1312/5000 [48:31<1:03:04,  1.03s/it]

616000 totalt klara...

Chunk 1:  26%|███████▎                    | 1313/5000 [48:35<2:09:39,  2.11s/it]

Checkpoint sparad (616000)

Chunk 1:  36%|██████████▏                 | 1812/5000 [1:34:08<58:55,  1.11s/it]

616500 totalt klara...

Chunk 1:  36%|█████████▍                | 1813/5000 [1:34:12<1:46:43,  2.01s/it]

Checkpoint sparad (616500)

Chunk 1:  46%|████████████              | 2312/5000 [1:51:54<4:01:15,  5.39s/it]

617000 totalt klara...

Chunk 1:  46%|████████████              | 2313/5000 [1:52:02<4:45:02,  6.37s/it]

Checkpoint sparad (617000)

Chunk 1:  56%|███████████████▋            | 2812/5000 [2:46:57<59:10,  1.62s/it]

617500 totalt klara...

Chunk 1:  56%|███████████████▊            | 2814/5000 [2:47:00<49:16,  1.35s/it]

Checkpoint sparad (617500)

Chunk 1:  66%|██████████████████▌         | 3312/5000 [3:54:22<45:52,  1.63s/it]

618000 totalt klara...

Chunk 1:  66%|█████████████████▏        | 3313/5000 [3:54:27<1:12:31,  2.58s/it]

Checkpoint sparad (618000)

Chunk 2:  26%|███████▎                    | 1312/5000 [40:11<1:21:15,  1.32s/it]

621000 totalt klara...

Chunk 2:  26%|███████▎                    | 1313/5000 [40:15<2:02:37,  2.00s/it]

Checkpoint sparad (621000)

Chunk 2:  36%|██████████▊                   | 1812/5000 [49:17<45:01,  1.18it/s]

621500 totalt klara...

Chunk 2:  36%|██████████▏                 | 1813/5000 [49:19<1:12:23,  1.36s/it]

Checkpoint sparad (621500)

Chunk 2:  46%|█████████████▊                | 2312/5000 [57:58<40:03,  1.12it/s]

622000 totalt klara...

Chunk 2:  46%|█████████████▉                | 2313/5000 [58:00<48:53,  1.09s/it]

Checkpoint sparad (622000)

Chunk 2:  56%|███████████████▋            | 2812/5000 [1:06:48<34:07,  1.07it/s]

622500 totalt klara...

Chunk 2:  56%|███████████████▊            | 2813/5000 [1:06:51<54:18,  1.49s/it]

Checkpoint sparad (622500)

Chunk 2:  66%|██████████████████▌         | 3312/5000 [1:15:35<22:38,  1.24it/s]

623000 totalt klara...

Chunk 2:  66%|██████████████████▌         | 3313/5000 [1:15:41<58:36,  2.08s/it]

Checkpoint sparad (623000)

Chunk 2:  76%|█████████████████████▎      | 3812/5000 [1:24:17<20:22,  1.03s/it]

623500 totalt klara...

Chunk 2:  76%|█████████████████████▎      | 3813/5000 [1:24:19<24:37,  1.24s/it]

Checkpoint sparad (623500)

Chunk 2:  86%|████████████████████████▏   | 4312/5000 [1:33:01<15:18,  1.33s/it]

624000 totalt klara...

Chunk 2:  86%|████████████████████████▏   | 4313/5000 [1:33:05<23:33,  2.06s/it]

Checkpoint sparad (624000)

Chunk 2:  96%|██████████████████████████▉ | 4812/5000 [1:41:49<01:49,  1.71it/s]

624500 totalt klara...

Chunk 2:  96%|██████████████████████████▉ | 4813/5000 [1:41:52<03:54,  1.26s/it]

Checkpoint sparad (624500)

Chunk 2: 100%|████████████████████████████| 5000/5000 [1:44:48<00:00,  1.26s/it]

Startar chunk 3 (5000 URL:er)

Chunk 3:  16%|████▋                        | 812/5000 [31:45<1:58:28,  1.70s/it]

625500 totalt klara...

Chunk 3:  16%|████▋                        | 813/5000 [31:46<1:54:45,  1.64s/it]

Checkpoint sparad (625500)

Chunk 3:  26%|███████▊                      | 1312/5000 [40:07<48:26,  1.27it/s]

626000 totalt klara...

Chunk 3:  26%|███████▉                      | 1313/5000 [40:08<55:38,  1.10it/s]

Checkpoint sparad (626000)

Chunk 3:  36%|██████████▊                   | 1812/5000 [48:24<47:39,  1.11it/s]

626500 totalt klara...

Chunk 3:  36%|██████████▉                   | 1813/5000 [48:25<51:53,  1.02it/s]

Checkpoint sparad (626500)

Chunk 3:  46%|█████████████▊                | 2312/5000 [56:47<41:44,  1.07it/s]

627000 totalt klara...

Chunk 3:  46%|█████████████▉                | 2313/5000 [56:49<49:28,  1.10s/it]

Checkpoint sparad (627000)

Chunk 3:  56%|███████████████▋            | 2812/5000 [1:05:19<36:07,  1.01it/s]

627500 totalt klara...

Chunk 3:  56%|███████████████▊            | 2813/5000 [1:05:21<53:36,  1.47s/it]

Checkpoint sparad (627500)

Chunk 3:  66%|██████████████████▌         | 3312/5000 [2:55:21<14:37,  1.92it/s]

628000 totalt klara...

Chunk 3:  66%|██████████████████▌         | 3313/5000 [2:55:23<23:37,  1.19it/s]

Checkpoint sparad (628000)

Chunk 3:  76%|█████████████████████▎      | 3812/5000 [3:03:39<17:31,  1.13it/s]

628500 totalt klara...

Chunk 3:  76%|█████████████████████▎      | 3813/5000 [3:03:41<23:44,  1.20s/it]

Checkpoint sparad (628500)

Chunk 3:  86%|████████████████████████▏   | 4312/5000 [3:12:09<17:19,  1.51s/it]

629000 totalt klara...

Chunk 3:  86%|████████████████████████▏   | 4313/5000 [3:12:11<16:42,  1.46s/it]

Checkpoint sparad (629000)

Chunk 3: 100%|████████████████████████████| 5000/5000 [3:23:19<00:00,  2.44s/it]

Startar chunk 4 (5000 URL:er)

Chunk 4:   6%|█▉                             | 312/5000 [05:17<39:03,  2.00it/s]

630000 totalt klara...

Chunk 4:   6%|█▉                             | 313/5000 [05:18<58:20,  1.34it/s]

Checkpoint sparad (630000)

Chunk 4:  16%|█████                          | 812/5000 [14:13<57:31,  1.21it/s]

630500 totalt klara...

Chunk 4:  16%|████▋                        | 813/5000 [14:14<1:10:47,  1.01s/it]

Checkpoint sparad (630500)

Chunk 4:  26%|███████▊                      | 1312/5000 [22:30<31:05,  1.98it/s]

631000 totalt klara...

Chunk 4:  26%|███████▉                      | 1313/5000 [22:32<41:58,  1.46it/s]

Checkpoint sparad (631000)

Chunk 4:  36%|██████████▊                   | 1812/5000 [30:47<26:41,  1.99it/s]

631500 totalt klara...

Chunk 4:  36%|██████████▉                   | 1813/5000 [30:48<36:46,  1.44it/s]

Checkpoint sparad (631500)

Chunk 4:  46%|█████████████▊                | 2312/5000 [39:06<23:14,  1.93it/s]

632000 totalt klara...

Chunk 4:  46%|█████████████▉                | 2313/5000 [39:07<30:01,  1.49it/s]

Checkpoint sparad (632000)

Chunk 4:  56%|████████████████▊             | 2812/5000 [48:04<44:02,  1.21s/it]

632500 totalt klara...

Chunk 4:  56%|████████████████▉             | 2813/5000 [48:06<47:50,  1.31s/it]

Checkpoint sparad (632500)

Chunk 4:  59%|█████████████████▊            | 2959/5000 [50:07<53:38,  1.58s/it]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Chunk 9:  66%|███████████████████▊          | 3312/5000 [56:01<15:11,  1.85it/s]

658000 totalt klara...

Chunk 9:  66%|███████████████████▉          | 3313/5000 [56:01<16:40,  1.69it/s]

Checkpoint sparad (658000)

Chunk 9:  76%|█████████████████████▎      | 3812/5000 [1:04:16<11:08,  1.78it/s]

658500 totalt klara...

Chunk 9:  76%|█████████████████████▎      | 3813/5000 [1:04:17<12:53,  1.53it/s]

Checkpoint sparad (658500)

Chunk 9:  86%|████████████████████████▏   | 4312/5000 [1:31:03<06:34,  1.74it/s]

659000 totalt klara...

Chunk 9:  86%|████████████████████████▏   | 4313/5000 [1:31:05<10:19,  1.11it/s]

Checkpoint sparad (659000)

Chunk 9:  96%|██████████████████████████▉ | 4812/5000 [3:02:27<09:10,  2.93s/it]

659500 totalt klara...

Chunk 9:  96%|██████████████████████████▉ | 4813/5000 [3:02:28<07:27,  2.40s/it]

Checkpoint sparad (659500)

Chunk 9: 100%|████████████████████████████| 5000/5000 [4:32:26<00:00,  3.27s/it]

Startar chunk 10 (5000 URL:er)

Chunk 10:   6%|█▋                          | 312/5000 [2:01:23<32:28,  2.41it/s]

660000 totalt klara...

Chunk 10:   6%|█▊                          | 313/5000 [2:01:25<59:17,  1.32it/s]

Checkpoint sparad (660000)

Chunk 10:  26%|███████                    | 1312/5000 [2:18:52<55:20,  1.11it/s]

661000 totalt klara...

Chunk 10:  26%|██████▌                  | 1313/5000 [2:18:55<1:27:17,  1.42s/it]

Checkpoint sparad (661000)

Chunk 10:  30%|███████▍                 | 1489/5000 [2:22:05<5:35:02,  5.73s/it]

KeyboardInterrupt:

In [43]:
cp = load_checkpoint()

print("Checkpoint rows:", len(cp))
print("Unika URL i checkpoint:", cp["url"].nunique())
print("Dubletter i checkpoint:", len(cp) - cp["url"].nunique())

Checkpoint rows: 661000
Unika URL i checkpoint: 614687
Dubletter i checkpoint: 46313

In [44]:
cp = load_checkpoint()

cp_clean = (
    cp.sort_index()
      .drop_duplicates(subset="url", keep="last")
)

print("Efter dedupe:", len(cp_clean))
print("Unika:", cp_clean["url"].nunique())

cp_clean.to_parquet("final.parquet")

Efter dedupe: 614687
Unika: 614687

In [49]:
cp = load_checkpoint()

print("Rader:", len(cp))
print("Unika URL:", cp["url"].nunique())

cp_clean = (
    cp
        .sort_index()
        .drop_duplicates(subset="url", keep="last")
        .reset_index(drop=True)
)

print("Efter dedupe:", len(cp_clean))

Rader: 661000
Unika URL: 614687
Efter dedupe: 614687

In [50]:
urls_wd = (
    df_riksdagen_wd["url"]
        .dropna()
        .astype(str)
        .unique()
)

print("WD unika:", len(urls_wd))
print("Checkpoint unika:", cp_clean["url"].nunique())

missing = set(urls_wd) - set(cp_clean["url"])
print("Saknade:", len(missing))

WD unika: 614687
Checkpoint unika: 614687
Saknade: 0

In [51]:
df_final = (
    df_riksdagen_wd
        .merge(
            cp_clean[["url", "status", "reason", "ia_url", "ia_status"]],
            on="url",
            how="left"
        )
)

In [52]:
print("WD rows:", len(df_riksdagen_wd))
print("Final rows:", len(df_final))

print("Status saknas:", df_final["status"].isna().sum())

WD rows: 617191
Final rows: 617191
Status saknas: 0

In [54]:
from datetime import date
import os

# Sätt datum
today = date.today().strftime("%Y_%m_%d")

# Se till att katalogen finns
os.makedirs("resultsRiksdagenWD", exist_ok=True)

# Bygg filnamn
outfile = f"resultsRiksdagenWD/links_Riksdagen_v1_Wikidata_{today}.csv"

In [55]:
df_final.to_csv(outfile, index=False, encoding="utf-8") 
print(f"[OK] Exported {len(df_riksdagen_wd)} rows to {outfile}")

[OK] Exported 617191 rows to resultsRiksdagenWD/links_Riksdagen_v1_Wikidata_2026_02_21.csv

In [46]:
cp_clean["url"].isna().sum()

0

In [56]:
def classify_link(row):
    if row["status"] == "ok":
        return "ok"
    if row["status"] == "dead":
        if row.get("ia_status") == "available":
            return "broken_archived"
        else:
            return "broken_lost"
    if row["status"] == "error":
        return "error"
    return "unknown"

df_final["link_status"] = df_final.apply(classify_link, axis=1)

In [57]:
df_final["link_status"].value_counts()

link_status
ok                 597816
broken_archived      9143
broken_lost          7159
error                3073
Name: count, dtype: int64

In [58]:
lang_stats = (
    df_final
        .groupby("lang")
        .agg(
            total_links=("url", "count"),
            broken_total=("link_status", lambda s: s.str.startswith("broken").sum()),
            broken_lost=("link_status", lambda s: (s == "broken_lost").sum()),
            archived=("link_status", lambda s: (s == "broken_archived").sum()),
            errors=("link_status", lambda s: (s == "error").sum()),
        )
        .reset_index()
)

lang_stats["broken_pct"] = (
    100 * lang_stats["broken_total"] / lang_stats["total_links"]
).round(1)

In [59]:
lang_stats

,lang,total_links,broken_total,broken_lost,archived,errors,broken_pct
0,special,617191,16302,7159,9143,3073,2.6

In [47]:
lang_stats = (
    df_riksdagen_wd
    .groupby("lang")
    .agg(
        total_links=("url", "count"),
        broken_links=("status", lambda s: (s == "dead").sum()),
        archived_links=("ia_status", lambda s: (s == "available").sum()),
    )
    .reset_index()
)

lang_stats["broken_pct"] = (
    100 * lang_stats["broken_links"] / lang_stats["total_links"]
).round(1)

lang_stats["broken_lost"] = (
    lang_stats["broken_links"] - lang_stats["archived_links"])

top10_langs = (
    lang_stats
    .sort_values("total_links", ascending=False)
    .head(10)
)
top10_langs[
    [
        "lang",
        "total_links",
        "broken_links",
        "broken_pct",
        "archived_links",
        "broken_lost",
    ]
]

KeyError: "Column(s) ['ia_status', 'status'] do not exist"

In [ ]:
from urllib.parse import urlparse

df = df_riksdagen_wd.copy()

df["domain"] = df["url"].apply(
    lambda u: urlparse(u).netloc.lower() if pd.notna(u) else None
)
domain_stats = (
    df
    .groupby("domain")
    .agg(
        total_links=("url", "count"),
        broken_links=("status", lambda s: (s == "dead").sum()),
        error_links=("status", lambda s: (s == "error").sum()),
    )
    .reset_index()
)
domain_stats["broken_pct"] = (
    100 * domain_stats["broken_links"] / domain_stats["total_links"]
).round(1)

domain_stats["error_pct"] = (
    100 * domain_stats["error_links"] / domain_stats["total_links"]
).round(1)

In [ ]:
status_counts = df["status"].value_counts()

num_ok = int(status_counts.get("ok", 0))
num_dead = int(status_counts.get("dead", 0))
num_error = int(status_counts.get("error", 0))
num_total = len(df)

pct_ok = round(100 * num_ok / num_total, 1)
pct_dead = round(100 * num_dead / num_total, 1)
pct_error = round(100 * num_error / num_total, 1)

# Broken links: archived vs lost
num_dead_archived = df[
    (df["status"] == "dead") & (df["ia_status"] == "available")
].shape[0]

num_dead_lost = num_dead - num_dead_archived

In [ ]:
top_domains = (
    domain_stats[domain_stats["total_links"] >= 5]
    .sort_values("total_links", ascending=False)
    .head(10)
)
domain_stats_html = "<ul>"
for _, r in top_domains.iterrows():
    domain_stats_html += (
        f"<li><strong>{r['domain']}</strong>: "
        f"{r['broken_links']} / {r['total_links']} broken "
        f"({r['broken_pct']}%)</li>"
    )
domain_stats_html += "</ul>"

In [62]:
def save_problem_report_wikidata_riksdagen(
    df,
    out_dir="resultsRiksdagenWD",
    issue_url="https://github.com/salgo60/SCB-Wikidata/issues/64",
):

    from pathlib import Path
    from datetime import date, datetime
    import pandas as pd
    from urllib.parse import urlparse, quote

    out_dir = Path(out_dir)
    out_dir.mkdir(exist_ok=True)

    today = date.today().strftime("%Y_%m_%d")
    out_path = out_dir / f"wikidata_riksdagen_problem_report_{today}.html"
    rerun_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    df = df.copy()

    # ------------------------------------------------
    # 1. Klassificera problem
    # ------------------------------------------------
    def classify(row):
        if row["status"] == "ok":
            return "ok"
        if row["status"] == "dead" and row.get("ia_status") == "available":
            return "broken_archived"
        if row["status"] == "dead":
            return "broken_lost"
        if row["status"] == "error":
            return "error"
        return "unknown"

    df["link_status"] = df.apply(classify, axis=1)

    # Endast problem
    df_problems = df[df["link_status"] != "ok"].copy()

    num_total = len(df)
    num_problem = len(df_problems)

    counts = df["link_status"].value_counts()

    num_archived = counts.get("broken_archived", 0)
    num_lost = counts.get("broken_lost", 0)
    num_error = counts.get("error", 0)

    pct_problem = round(100 * num_problem / num_total, 2)

    # ------------------------------------------------
    # 2. Severity
    # ------------------------------------------------
    severity_map = {
        "broken_lost": "critical",
        "broken_archived": "warning",
        "error": "technical"
    }

    df_problems["severity"] = df_problems["link_status"].map(severity_map)

    df_problems = df_problems.sort_values(
        ["severity"],
        ascending=[True]
    )

    # ------------------------------------------------
    # 3. Orsaksanalys
    # ------------------------------------------------
    reason_stats = (
        df_problems
        .groupby("reason")
        .size()
        .reset_index(name="count")
        .sort_values("count", ascending=False)
    )

    reason_table_html = reason_stats.to_html(
        classes="pivot",
        index=False,
        border=0
    )

    # ------------------------------------------------
    # 4. Domänanalys
    # ------------------------------------------------
    df_problems["domain"] = df_problems["url"].apply(
        lambda u: urlparse(u).netloc.lower() if pd.notna(u) else None
    )

    domain_stats = (
        df_problems
        .groupby("domain")
        .size()
        .reset_index(name="problem_count")
        .sort_values("problem_count", ascending=False)
    )

    domain_table_html = domain_stats.head(20).to_html(
        classes="pivot",
        index=False,
        border=0
    )

    # ------------------------------------------------
    # 5. HTML-tabell (endast problem)
    # ------------------------------------------------
    html_table = df_problems.to_html(
        classes="pivot",
        border=0,
        escape=False,
        index=False,
    )

    # ------------------------------------------------
    # 6. Executive summary
    # ------------------------------------------------
    meta_html = f"""
    <div class="meta">
      <h2>Problem Summary</h2>

      <p><strong>Run:</strong> {rerun_ts}</p>

      <p>
        <strong>Total links analyzed:</strong> {num_total}<br>
        <strong>Total problem links:</strong> {num_problem} ({pct_problem}%)<br><br>

        <strong style="color:#b71c1c;">Broken – lost:</strong> {num_lost}<br>
        <strong style="color:#c62828;">Broken – archived:</strong> {num_archived}<br>
        <strong style="color:#ef6c00;">Technical errors:</strong> {num_error}
      </p>

      <p>
        This report focuses on links stored in Wikidata that do not
        currently resolve to accessible content.
      </p>

      <p>
        The presence of unresolved links may indicate:
      </p>

      <ul>
        <li>Identifier instability</li>
        <li>Missing redirect policies</li>
        <li>Absence of tombstone pages</li>
        <li>Structural URL changes</li>
      </ul>

      <p><strong>Reference issue:</strong>
         <a href="{issue_url}" target="_blank">
         {issue_url.split("/")[-1]}</a>
      </p>
    </div>
    """

    # ------------------------------------------------
    # 7. Slutlig HTML
    # ------------------------------------------------
    html = f"""
    <html>
    <head>
      <meta charset="utf-8">
      <title>Wikidata – Riksdagen link integrity report</title>
      <style>
        body {{ font-family: Arial; margin: 20px; }}
        table.pivot {{ border-collapse: collapse; width: 100%; font-size: 12px; }}
        table.pivot th, table.pivot td {{
            border: 1px solid #999;
            padding: 6px;
        }}
        table.pivot th {{
            background: #f2f2f2;
        }}
        .meta {{
            background: #f8f8f8;
            border: 1px solid #ccc;
            padding: 12px;
            margin-bottom: 20px;
        }}
      </style>
    </head>
    <body>

      <h1>Wikidata → Riksdagen link integrity assessment</h1>

      {meta_html}

      <h2>Problem breakdown by cause</h2>
      {reason_table_html}

      <h2>Domains most affected</h2>
      {domain_table_html}

      <h2>Detailed problem list</h2>
      {html_table}

    </body>
    </html>
    """

    out_path.write_text(html, encoding="utf-8")
    print(f"✅ Problem report created: {out_path}")

In [63]:
save_problem_report_wikidata_riksdagen(df_final)

✅ Problem report created: resultsRiksdagenWD/wikidata_riksdagen_problem_report_2026_02_21.html

### Testa om errors som bl.a har timeout

In [64]:
df_errors = df_final[df_final["status"] == "error"].copy()

print("Antal error:", len(df_errors))

Antal error: 3073

In [65]:
urls_retry = df_errors["url"].unique().tolist()

In [66]:
# Sänk workers
MAX_WORKERS = 3
REQUEST_TIMEOUT = 30
RATE_LIMIT_PER_SEC = 1

In [67]:
def retry_errors(urls):

    results = []

    with ThreadPoolExecutor(max_workers=12) as ex:
        futures = {ex.submit(process_url, u): u for u in urls}

        for f in tqdm(as_completed(futures), total=len(futures)):
            res = f.result()
            results.append(res)

    return pd.DataFrame(results)

In [68]:
df_retry = retry_errors(urls_retry)

100%|█████████████████████████████████████| 3066/3066 [2:25:11<00:00,  2.84s/it]

In [69]:
df_retry = df_retry.drop_duplicates(subset="url", keep="last")

df_final_updated = df_final.merge(
    df_retry[["url", "status", "reason", "ia_url", "ia_status"]],
    on="url",
    how="left",
    suffixes=("", "_retry")
)

# Om retry gav bättre status → ersätt
mask = df_final_updated["status"] == "error"

for col in ["status", "reason", "ia_url", "ia_status"]:
    df_final_updated.loc[mask, col] = df_final_updated.loc[mask, f"{col}_retry"]

In [77]:
def save_problem_report_wikidata_riksdagen(
    df,
    out_dir="resultsRiksdagenWD",
    issue_url="https://github.com/salgo60/SCB-Wikidata/issues/64",
):

    from pathlib import Path
    from datetime import date, datetime
    import pandas as pd
    from urllib.parse import urlparse

    out_dir = Path(out_dir)
    out_dir.mkdir(exist_ok=True)

    today = date.today().strftime("%Y_%m_%d")
    out_path = out_dir / f"wikidata_riksdagen_problem_report_{today}.html"
    rerun_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    df = df.copy()

    # ------------------------------------------------
    # Klassificering
    # ------------------------------------------------
    def classify(row):
        if row["status"] == "ok":
            return "ok"
        if row["status"] == "dead" and row.get("ia_status") == "available":
            return "broken_archived"
        if row["status"] == "dead":
            return "broken_lost"
        if row["status"] == "error":
            return "error"
        return "unknown"

    df["link_status"] = df.apply(classify, axis=1)

    df_problems = df[df["link_status"] != "ok"].copy()

    num_total = len(df)
    num_problem = len(df_problems)

    counts = df["link_status"].value_counts()
    num_archived = counts.get("broken_archived", 0)
    num_lost = counts.get("broken_lost", 0)
    num_error = counts.get("error", 0)

    pct_problem = round(100 * num_problem / num_total, 2)

    # ------------------------------------------------
    # Orsaksanalys
    # ------------------------------------------------
    reason_stats = (
        df_problems
        .groupby("reason")
        .size()
        .reset_index(name="count")
        .sort_values("count", ascending=False)
    )

    reason_table_html = reason_stats.to_html(
        classes="pivot",
        index=False,
        border=0
    )

    # ------------------------------------------------
    # Render Wikidata Q-id som länk
    # ------------------------------------------------
    if "page_title" in df_problems.columns:
        df_problems.rename(columns={"page_title": "Wikidata"}, inplace=True)

        df_problems["Wikidata"] = df_problems["Wikidata"].apply(
            lambda q: f'<a href="https://www.wikidata.org/wiki/{q}" target="_blank">{q}</a>'
            if pd.notna(q) and str(q).startswith("Q")
            else q
        )

    # ------------------------------------------------
    # Gör url klickbar
    # ------------------------------------------------
    df_problems["url"] = df_problems["url"].apply(
        lambda u: f'<a href="{u}" target="_blank">{u}</a>'
        if pd.notna(u)
        else ""
    )

    # ------------------------------------------------
    # IA ikon
    # ------------------------------------------------
    def render_ia_icon(row):
        if row.get("ia_status") == "available" and row.get("ia_url"):
            return (
                f'<a href="{row["ia_url"]}" target="_blank" '
                f'title="Archived copy">'
                f'📦</a>'
            )
        return ""

    df_problems["Archive"] = df_problems.apply(render_ia_icon, axis=1)

    # Ta bort kolumner som inte behövs
    drop_cols = ["lang", "wiki_link"]
    for col in drop_cols:
        if col in df_problems.columns:
            df_problems.drop(columns=[col], inplace=True)

    # ------------------------------------------------
    # HTML-tabell
    # ------------------------------------------------
    html_table = df_problems.to_html(
        classes="pivot",
        border=0,
        escape=False,
        index=False,
    )

    # ------------------------------------------------
    # Executive summary
    # ------------------------------------------------
    meta_html = f"""
    <div class="meta">
      <h2>Executive Summary</h2>

      <p><strong>Run:</strong> {rerun_ts}</p>

      <p>
        <strong>Total links analyzed:</strong> {num_total}<br>
        <strong>Links with issues:</strong> {num_problem} ({pct_problem}%)<br><br>

        <strong style="color:#b71c1c;">Broken – lost:</strong> {num_lost}<br>
        <strong style="color:#c62828;">Broken – archived:</strong> {num_archived}<br>
        <strong style="color:#ef6c00;">Technical errors:</strong> {num_error}
      </p>

      <p>
        This report lists Wikidata items whose stored riksdagen.se links
        do not currently resolve to accessible content.
      </p>

      <p><strong>Reference issue:</strong>
         <a href="{issue_url}" target="_blank">
         {issue_url.split("/")[-1]}</a>
      </p>
    </div>
    """

    # ------------------------------------------------
    # HTML-dokument
    # ------------------------------------------------
    html = f"""
    <html>
    <head>
      <meta charset="utf-8">
      <title>Wikidata – Riksdagen link integrity</title>
      <style>
        body {{ font-family: Arial; margin: 20px; }}
        table.pivot {{ border-collapse: collapse; width: 100%; font-size: 12px; }}
        table.pivot th, table.pivot td {{
            border: 1px solid #999;
            padding: 6px;
        }}
        table.pivot th {{ background: #f2f2f2; }}
        .meta {{
            background: #f8f8f8;
            border: 1px solid #ccc;
            padding: 12px;
            margin-bottom: 20px;
        }}
      </style>
    </head>
    <body>

      <h1>Wikidata → Riksdagen non-resolving links</h1>

      {meta_html}

      <h2>Problem breakdown by cause</h2>
      {reason_table_html}

      <h2>Detailed list (non-resolving links only)</h2>
      {html_table}

    </body>
    </html>
    """

    out_path.write_text(html, encoding="utf-8")
    print(f"✅ Problem report created: {out_path}")

In [86]:
def save_problem_report_wikidata_riksdagen(
    df,
    out_dir="resultsRiksdagenWD",
    issue_url="https://github.com/salgo60/SCB-Wikidata/issues/64",
):

    from pathlib import Path
    from datetime import date, datetime
    import pandas as pd
    from urllib.parse import urlparse

    out_dir = Path(out_dir)
    out_dir.mkdir(exist_ok=True)

    today = date.today().strftime("%Y_%m_%d")
    out_path = out_dir / f"wikidata_riksdagen_problem_report_{today}.html"
    rerun_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    df = df.copy()

    # ------------------------------------------------
    # Klassificering
    # ------------------------------------------------
    def classify(row):
        if row["status"] == "ok":
            return "ok"
        if row["status"] == "dead" and row.get("ia_status") == "available":
            return "broken_archived"
        if row["status"] == "dead":
            return "broken_lost"
        if row["status"] == "error":
            return "error"
        return "unknown"

    df["link_status"] = df.apply(classify, axis=1)

    df_problems = df[df["link_status"] != "ok"].copy()

    num_total = len(df)
    num_problem = len(df_problems)

    counts = df["link_status"].value_counts()
    num_archived = counts.get("broken_archived", 0)
    num_lost = counts.get("broken_lost", 0)
    num_error = counts.get("error", 0)

    pct_problem = round(100 * num_problem / num_total, 2)

    # ------------------------------------------------
    # Orsaksanalys
    # ------------------------------------------------
    reason_stats = (
        df_problems
        .groupby("reason")
        .size()
        .reset_index(name="count")
        .sort_values("count", ascending=False)
    )

    reason_table_html = reason_stats.to_html(
        classes="pivot",
        index=False,
        border=0
    )

    from urllib.parse import quote
    # ------------------------------------------------
    # Gör Wikidata-kolumn klickbar (alla typer)
    # ------------------------------------------------
    if "page_title" in df_problems.columns:
        df_problems.rename(columns={"page_title": "Wikidata"}, inplace=True)
    
    if "Wikidata" in df_problems.columns:
        df_problems["Wikidata"] = df_problems["Wikidata"].apply(
            lambda v: (
                f'<a href="https://www.wikidata.org/wiki/{quote(str(v))}" '
                f'target="_blank">{v}</a>'
            )
            if pd.notna(v)
            else ""
        )
    # ------------------------------------------------
    # Gör url klickbar
    # ------------------------------------------------
    df_problems["url"] = df_problems["url"].apply(
        lambda u: f'<a href="{u}" target="_blank">{u}</a>'
        if pd.notna(u)
        else ""
    )

    # ------------------------------------------------
    # IA ikon
    # ------------------------------------------------
    def render_ia_icon(row):
        if row.get("ia_status") == "available" and row.get("ia_url"):
            return (
                f'<a href="{row["ia_url"]}" target="_blank" '
                f'title="Archived copy">'
                f'📦</a>'
            )
        return ""

    df_problems["Archive"] = df_problems.apply(render_ia_icon, axis=1)

    # Ta bort kolumner som inte behövs
    drop_cols = ["lang", "wiki_link"]
    for col in drop_cols:
        if col in df_problems.columns:
            df_problems.drop(columns=[col], inplace=True)
    # ------------------------------------------------
    # IA ikon (ersätter ia_url)
    # ------------------------------------------------
    def render_ia_icon(row):
        if row.get("ia_status") == "available" and row.get("ia_url"):
            return (
                f'<a href="{row["ia_url"]}" target="_blank" '
                f'title="Archived copy (Internet Archive)">'
                f'📦</a>'
            )
        return ""
    
    df_problems["Archive"] = df_problems.apply(render_ia_icon, axis=1)

    # ------------------------------------------------
    # Ta bort råkolumner som inte ska visas
    # ------------------------------------------------
    cols_to_remove = ["ia_url", "ia_status", "severity_rank"]
    
    for col in cols_to_remove:
        if col in df_problems.columns:
            df_problems.drop(columns=[col], inplace=True)
    
    # ------------------------------------------------
    # Välj exakt kolumnordning
    # ------------------------------------------------
    wanted_columns = [
        "Wikidata",
        "url",
        "status",
        "reason",
        "Archive",
        "link_status"
    ]
    
    existing = [c for c in wanted_columns if c in df_problems.columns]
    
    df_problems = df_problems[existing]
    # ------------------------------------------------
    # Ta bort råkolumner som inte ska visas
    # ------------------------------------------------
    cols_to_remove = ["ia_url", "ia_status", "severity_rank"]
    
    for col in cols_to_remove:
        if col in df_problems.columns:
            df_problems.drop(columns=[col], inplace=True)
    
    # ------------------------------------------------
    # Välj exakt kolumnordning
    # ------------------------------------------------
    wanted_columns = [
        "Wikidata",
        "url",
        "status",
        "reason",
        "Archive",
        "link_status"
    ]
    
    existing = [c for c in wanted_columns if c in df_problems.columns]
    
    df_problems = df_problems[existing]
    # ------------------------------------------------
    # HTML-tabell
    # ------------------------------------------------
    html_table = df_problems.to_html(
        classes="pivot",
        border=0,
        escape=False,
        index=False,
    )

    # ------------------------------------------------
    # Executive summary
    # ------------------------------------------------
    meta_html = f"""
    <div class="meta">
      <h2>Executive Summary</h2>

      <p><strong>Run:</strong> {rerun_ts}</p>

      <p>
        <strong>Total links analyzed:</strong> {num_total}<br>
        <strong>Links with issues:</strong> {num_problem} ({pct_problem}%)<br><br>

        <strong style="color:#b71c1c;">Broken – lost:</strong> {num_lost}<br>
        <strong style="color:#c62828;">Broken – archived:</strong> {num_archived}<br>
        <strong style="color:#ef6c00;">Technical errors:</strong> {num_error}
      </p>

      <p>
        This report lists Wikidata items whose stored riksdagen.se links
        do not currently resolve to accessible content.
      </p>

      <p><strong>Reference issue:</strong>
         <a href="{issue_url}" target="_blank">
         {issue_url.split("/")[-1]}</a>
      </p>
    </div>
    """

    # ------------------------------------------------
    # HTML-dokument
    # ------------------------------------------------
    html = f"""
    <html>
    <head>
      <meta charset="utf-8">
      <title>Wikidata – Riksdagen link integrity</title>
      <style>
        body {{ font-family: Arial; margin: 20px; }}
        table.pivot {{ border-collapse: collapse; width: 100%; font-size: 12px; }}
        table.pivot th, table.pivot td {{
            border: 1px solid #999;
            padding: 6px;
        }}
        table.pivot th {{ background: #f2f2f2; }}
        .meta {{
            background: #f8f8f8;
            border: 1px solid #ccc;
            padding: 12px;
            margin-bottom: 20px;
        }}
      </style>
    </head>
    <body>

      <h1>Wikidata → Riksdagen non-resolving links</h1>

      {meta_html}

      <h2>Problem breakdown by cause</h2>
      {reason_table_html}

      <h2>Detailed list (non-resolving links only)</h2>
      {html_table}

    </body>
    </html>
    """

    out_path.write_text(html, encoding="utf-8")
    print(f"✅ Problem report created: {out_path}")

In [94]:
df_problems = df_final_updated[df_final_updated["link_status"] != "ok"] 
df_problems.info() 
df_problems.head()

<class 'pandas.core.frame.DataFrame'>
Index: 19375 entries, 5 to 617185
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   lang             19375 non-null  object
 1   page_title       19375 non-null  object
 2   url              19375 non-null  object
 3   wiki_link        19375 non-null  object
 4   status           19375 non-null  object
 5   reason           16555 non-null  object
 6   ia_url           9306 non-null   object
 7   ia_status        19375 non-null  object
 8   link_status      19375 non-null  object
 9   status_retry     3073 non-null   object
 10  reason_retry     253 non-null    object
 11  ia_url_retry     163 non-null    object
 12  ia_status_retry  3073 non-null   object
dtypes: object(13)
memory usage: 2.1+ MB

,lang,page_title,url,wiki_link,status,reason,ia_url,ia_status,link_status,status_retry,reason_retry,ia_url_retry,ia_status_retry
5,special,Wikidata:Property proposal/Archive/20,http://www.riksdagen.se/sv/ledamoter-partier/H...,https://special.wikipedia.org/wiki/Wikidata:Pr...,dead,HTTP 404,http://web.archive.org/web/20160303234228/http...,available,broken_archived,NaN,NaN,NaN,NaN
6,special,Q2740012,http://www.riksdagen.se/en/Members-and-parties...,https://special.wikipedia.org/wiki/Q2740012,dead,HTTP 404,http://web.archive.org/web/20160303235945/http...,available,broken_archived,NaN,NaN,NaN,NaN
7,special,Q18202407,http://www.riksdagen.se/sv/ledamoter-partier/I...,https://special.wikipedia.org/wiki/Q18202407,dead,HTTP 404,http://web.archive.org/web/20180902025345/http...,available,broken_archived,NaN,NaN,NaN,NaN
8,special,Q2740012,https://www.riksdagen.se/sv/ledamoter-partier/...,https://special.wikipedia.org/wiki/Q2740012,dead,HTTP 404,http://web.archive.org/web/20160407193603/http...,available,broken_archived,NaN,NaN,NaN,NaN
64,special,Property:P1214,http://data.riksdagen.se/Data/Ledamoter,https://special.wikipedia.org/wiki/Property:P1214,dead,HTTP 404,http://web.archive.org/web/20230604005232/http...,available,broken_archived,NaN,NaN,NaN,NaN

In [96]:
import requests
import time

WIKIDATA_SPARQL = "https://query.wikidata.org/sparql"

def fetch_sv_labels_sparql(qids, batch_size=200, sleep=0.2):
    label_map = {}

    headers = {
        "User-Agent": "LinkAudit/1.0 (research; salgo60@msn.com)"
    }

    for i in range(0, len(qids), batch_size):
        batch = qids[i:i+batch_size]

        values = " ".join(f"wd:{qid}" for qid in batch)

        query = f"""
        SELECT ?item ?itemLabel WHERE {{
          VALUES ?item {{ {values} }}
          SERVICE wikibase:label {{ bd:serviceParam wikibase:language "sv,en". }}
        }}
        """

        r = requests.get(
            WIKIDATA_SPARQL,
            params={"query": query, "format": "json"},
            headers=headers,
            timeout=30,
        )

        data = r.json()

        for row in data["results"]["bindings"]:
            qid = row["item"]["value"].split("/")[-1]
            label = row["itemLabel"]["value"]
            label_map[qid] = label

        time.sleep(sleep)

    return label_map

In [98]:
# Extrahera råa Q-id (utan HTML)
df_problems["qid_raw"] = df_problems["page_title"].str.replace(
    r'<.*?>', '', regex=True
)

qids = [
    q for q in df_problems["qid_raw"].dropna().unique()
    if str(q).startswith("Q")
]

print("Unika Q-id:", len(qids))

label_map = fetch_sv_labels_sparql(qids)

df_problems["Titelsv"] = df_problems["qid_raw"].map(label_map)

/var/folders/fd/md6r13sj0wsbg_6_xl160d300000gn/T/ipykernel_5107/313595599.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_problems["qid_raw"] = df_problems["page_title"].str.replace(

Unika Q-id: 17203

/var/folders/fd/md6r13sj0wsbg_6_xl160d300000gn/T/ipykernel_5107/313595599.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_problems["Titelsv"] = df_problems["qid_raw"].map(label_map)

In [99]:
save_problem_report_wikidata_riksdagen(df_final_updated)

✅ Problem report created: resultsRiksdagenWD/wikidata_riksdagen_problem_report_2026_02_23.html

In [104]:
save_problem_report_wikidata_riksdagen(df_problems)

✅ Problem report created: resultsRiksdagenWD/wikidata_riksdagen_problem_report_2026_02_23.html

In [ ]:
 # End timer and calculate duration
end_time = time.time()
elapsed_time = end_time - start_time# Bygg audit-lager för den här etappen

# Print current date and total time
print("Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
minutes, seconds = divmod(elapsed_time, 60)
print("Total time elapsed: {:02.0f} minutes {:05.2f} seconds".format(minutes, seconds))